// 词库级冲突组 v1（人工语义判断）。
// 覆盖四个来源：当前 words.json、已复核四字词、三字词策展、两字 KEEP_CANDIDATE。
// 只标记冲突供下一轮人工取舍，不自动删除任何词。
// type ∈ near-synonym | same-drawing | granularity | phrase-variant。
// words 中的词可能来自游戏库（标注 bank）或候选（按各策展产物）。
export default [
  // —— 四字词内部（沿用已复核文件标注的三组 + 补充）——
  { type: "near-synonym", words: ["一望无边", "一望无际"], recommendation: "review-one-or-both", reason: "四字近义，画面同为极目远眺的天际线，建议二选一。" },
  { type: "near-synonym", words: ["筋疲力尽", "精疲力竭"], recommendation: "review-one-or-both", reason: "同为瘫坐喘息的疲惫画面，已复核文件倾向保留前者。" },
  { type: "near-synonym", words: ["惊天动地", "震天动地"], recommendation: "review-one-or-both", reason: "同为巨响震动的夸张画面，几乎不可区分。" },
  { type: "same-drawing", words: ["哄堂大笑", "哈哈大笑"], recommendation: "review-one-or-both", reason: "同为众人大笑场面，画出来无法区分。" },
  { type: "same-drawing", words: ["心惊肉跳", "心惊胆战"], recommendation: "review-one-or-both", reason: "同为受惊捂胸表情，画面高度重合。" },
  { type: "same-drawing", words: ["威风凛凛", "威武"], recommendation: "review-one-or-both", reason: "同为昂首挺立的威风形象。" },
  { type: "granularity", words: ["大吃一惊", "吃惊", "惊奇", "惊叹"], recommendation: "review-one-or-both", reason: "惊讶表情家族：四字/双字并存会互相抢答，需控制数量。" },
  { type: "phrase-variant", words: ["急急忙忙", "慌忙", "赶紧"], recommendation: "review-one-or-both", reason: "匆忙奔走画面相同，词形长短不同。" },
  { type: "same-drawing", words: ["闪闪发光", "闪烁", "亮晶晶", "晶莹"], recommendation: "review-one-or-both", reason: "发光/闪亮视觉符号相同，状态词扎堆。" },

  // —— 三字词 ↔ 词库/两字候选 ——
  { type: "near-synonym", words: ["司机", "驾驶员"], recommendation: "review-one-or-both", reason: "开车画面完全相同，儿童更常答『司机』。" },
  { type: "near-synonym", words: ["渔夫", "渔民"], recommendation: "review-one-or-both", reason: "撒网捕鱼画面相同。" },
  { type: "granularity", words: ["灯", "电灯泡"], recommendation: "review-one-or-both", reason: "灯泡即灯的具体化，画面高度重合。" },
  { type: "same-drawing", words: ["火烧云", "朝霞", "晚霞"], recommendation: "review-one-or-both", reason: "同为天空红霞，早晚方向难以画分。" },
  { type: "same-drawing", words: ["暴风雨", "雷雨", "阵雨", "风暴"], recommendation: "review-one-or-both", reason: "风雨大作画面相同，天气词需控制粒度。" },
  { type: "near-synonym", words: ["丹顶鹤", "白鹤"], recommendation: "review-one-or-both", reason: "白色鹤类形象几乎一致。" },
  { type: "granularity", words: ["石头", "鹅卵石"], recommendation: "review-one-or-both", reason: "卵石是石头的具体化，溪边场景重合。" },
  { type: "same-drawing", words: ["石钟乳", "石笋"], recommendation: "review-one-or-both", reason: "同为溶洞场景，一垂一立，儿童难以区分。" },
  { type: "same-drawing", words: ["荷花", "睡莲"], recommendation: "review-one-or-both", reason: "浮水莲花与荷花在儿童画中无法区分。" },
  { type: "same-drawing", words: ["暖和", "温暖", "温和", "暖洋洋"], recommendation: "review-one-or-both", reason: "暖意场景（晒太阳/围炉）高度重合。" },
  { type: "same-drawing", words: ["安静", "宁静", "寂静", "肃静", "清静", "静悄悄"], recommendation: "review-one-or-both", reason: "无声场景家族，六词一画，建议最多留一两个。" },

  // —— 两字候选 ↔ 词库 ——
  { type: "near-synonym", words: ["宇宙", "太空"], recommendation: "review-one-or-both", reason: "星空星球画面相同，语义近同。" },
  { type: "same-drawing", words: ["星星", "星空", "繁星", "群星"], recommendation: "review-one-or-both", reason: "满天星斗画面一致。" },
  { type: "granularity", words: ["白云", "乌云", "云彩"], recommendation: "review-one-or-both", reason: "云的三种表达，乌云有明暗对比尚可区分，云彩与白云重合。" },
  { type: "granularity", words: ["天空", "蓝天"], recommendation: "review-one-or-both", reason: "晴空画面相同。" },
  { type: "same-drawing", words: ["春天", "春光", "春日"], recommendation: "review-one-or-both", reason: "春日花开画面相同。" },
  { type: "same-drawing", words: ["夏天", "炎夏", "炎热", "酷暑"], recommendation: "review-one-or-both", reason: "烈日场景家族重合。" },
  { type: "same-drawing", words: ["冬天", "严寒"], recommendation: "review-one-or-both", reason: "冰雪场景重合。" },
  { type: "same-drawing", words: ["夜晚", "黑夜", "深夜"], recommendation: "review-one-or-both", reason: "夜景画面一致，仅程度不同。" },
  { type: "same-drawing", words: ["黄昏", "黎明"], recommendation: "review-one-or-both", reason: "天际霞光方向难以画分。" },
  { type: "same-drawing", words: ["早晨", "清晨", "晌午"], recommendation: "review-one-or-both", reason: "日升时段画面相近。" },
  { type: "granularity", words: ["太阳", "阳光", "光芒"], recommendation: "review-one-or-both", reason: "发光太阳画面重合。" },
  { type: "granularity", words: ["月亮", "满月"], recommendation: "review-one-or-both", reason: "圆月画面相同。" },
  { type: "granularity", words: ["房子", "住宅", "宅院", "茅屋", "院墙"], recommendation: "review-one-or-both", reason: "房屋居所家族，画面以『一座房』为主。" },
  { type: "granularity", words: ["草地", "草坪", "草丛"], recommendation: "review-one-or-both", reason: "草地质画面重合。" },
  { type: "same-drawing", words: ["沙滩", "河滩", "海滨"], recommendation: "review-one-or-both", reason: "水岸沙地画面相同。" },
  { type: "granularity", words: ["花朵", "花瓣", "鲜花", "野花", "花丛", "盛开"], recommendation: "review-one-or-both", reason: "花的泛称家族，建议以具体花种为主。" },
  { type: "granularity", words: ["床", "床铺"], recommendation: "review-one-or-both", reason: "床铺画面与床重合。" },
  { type: "granularity", words: ["椅子", "板凳", "座位"], recommendation: "review-one-or-both", reason: "坐具家族画面重合。" },
  { type: "granularity", words: ["书包", "背包"], recommendation: "review-one-or-both", reason: "双肩包画面重合。" },
  { type: "granularity", words: ["台阶", "梯子", "楼梯"], recommendation: "review-one-or-both", reason: "台阶踏步画面重合。" },
  { type: "granularity", words: ["马路", "公路", "道路", "街道"], recommendation: "review-one-or-both", reason: "道路家族，画面均为一条路。" },
  { type: "phrase-variant", words: ["唱歌", "歌唱", "歌声"], recommendation: "review-one-or-both", reason: "引吭高歌画面相同。" },
  { type: "phrase-variant", words: ["跳舞", "舞蹈"], recommendation: "review-one-or-both", reason: "翩翩起舞画面相同。" },
  { type: "same-drawing", words: ["吃饭", "晚饭", "饭菜", "美食", "美餐"], recommendation: "review-one-or-both", reason: "满桌饭菜画面相同。" },
  { type: "same-drawing", words: ["睡觉", "沉睡", "苏醒", "醒来"], recommendation: "review-one-or-both", reason: "睡眠家族画面重合。" },
  { type: "same-drawing", words: ["拍手", "掌声"], recommendation: "review-one-or-both", reason: "鼓掌画面相同。" },
  { type: "same-drawing", words: ["拥抱", "依偎", "亲密"], recommendation: "review-one-or-both", reason: "相依相拥画面相同。" },
  { type: "same-drawing", words: ["哭泣", "眼泪", "泪水"], recommendation: "review-one-or-both", reason: "落泪画面相同。" },
  { type: "same-drawing", words: ["笑容", "笑脸", "微笑", "含笑", "笑呵呵", "笑嘻嘻"], recommendation: "review-one-or-both", reason: "笑的表情家族，画面高度重合。" },
  { type: "same-drawing", words: ["画画", "图画", "画册"], recommendation: "review-one-or-both", reason: "绘画场景重合。" },
  { type: "same-drawing", words: ["看书", "读书", "学习", "功课"], recommendation: "review-one-or-both", reason: "伏案读书画面相同。" },
  { type: "same-drawing", words: ["弹琴", "演奏", "琴键"], recommendation: "review-one-or-both", reason: "演奏乐器画面重合。" },
  { type: "same-drawing", words: ["跑步", "赛跑", "锻炼"], recommendation: "review-one-or-both", reason: "奔跑锻炼画面相同。" },
  { type: "same-drawing", words: ["扫地", "整理", "整洁", "清洁"], recommendation: "review-one-or-both", reason: "打扫收纳画面重合。" },
  { type: "same-drawing", words: ["拍照", "摄影", "拍摄"], recommendation: "review-one-or-both", reason: "举相机取景画面相同。" },
  { type: "same-drawing", words: ["观察", "审视", "观赏", "欣赏"], recommendation: "review-one-or-both", reason: "驻足观看画面重合。" },
  { type: "same-drawing", words: ["钓鱼", "钓竿"], recommendation: "review-one-or-both", reason: "垂钓画面相同。" },
  { type: "same-drawing", words: ["收割", "收成", "丰收"], recommendation: "review-one-or-both", reason: "秋收场景重合。" },
  { type: "same-drawing", words: ["种树", "植树", "树苗"], recommendation: "review-one-or-both", reason: "植苗栽树画面相同。" },
  { type: "same-drawing", words: ["山洞", "洞穴", "窟窿"], recommendation: "review-one-or-both", reason: "洞穴黑影画面重合。" },
  { type: "same-drawing", words: ["荒漠", "荒野", "荒凉"], recommendation: "review-one-or-both", reason: "荒芜场景重合。" },
  { type: "granularity", words: ["小河", "河水", "河流"], recommendation: "review-one-or-both", reason: "河流画面相同。" },
  { type: "same-drawing", words: ["救援", "救命"], recommendation: "review-one-or-both", reason: "呼救施救画面重合。" },
  { type: "granularity", words: ["温度计", "摄氏度"], recommendation: "review-one-or-both", reason: "画温度计只能猜温度计，单位无法表达。" },
  { type: "same-drawing", words: ["烛台", "蜡烛", "烛光"], recommendation: "review-one-or-both", reason: "烛火画面重合。" },
  { type: "same-drawing", words: ["灯笼", "花灯"], recommendation: "review-one-or-both", reason: "节庆花灯画面相同。" },
  { type: "same-drawing", words: ["医生看病", "治疗", "养病"], recommendation: "review-one-or-both", reason: "诊疗画面重合。" },
  { type: "same-drawing", words: ["老师讲课", "讲座", "讲桌"], recommendation: "review-one-or-both", reason: "讲授课场景重合。" },
  { type: "phrase-variant", words: ["旅行", "周游", "漫游"], recommendation: "review-one-or-both", reason: "远游画面相同。" },
  { type: "same-drawing", words: ["采访", "访问"], recommendation: "review-one-or-both", reason: "采访问答画面重合。" },
  { type: "same-drawing", words: ["演员", "表演"], recommendation: "review-one-or-both", reason: "登台表演画面重合。" },
  { type: "same-drawing", words: ["爷爷", "伯伯", "叔叔", "舅父", "姑父", "外祖父"], recommendation: "review-one-or-both", reason: "男性长辈亲属称谓，画面无法区分到具体称呼。" },
  { type: "same-drawing", words: ["妈妈", "母亲"], recommendation: "review-one-or-both", reason: "母子画面相同，保留口语词即可。" },
  { type: "same-drawing", words: ["爸爸", "父亲"], recommendation: "review-one-or-both", reason: "父子画面相同。" },
  { type: "same-drawing", words: ["婴儿", "幼儿"], recommendation: "review-one-or-both", reason: "婴幼画面重合。" },
  { type: "same-drawing", words: ["新娘", "结婚", "妻子", "媳妇"], recommendation: "review-one-or-both", reason: "婚礼场景家族，画面高度重合。" },
  { type: "granularity", words: ["毛毛虫", "毛虫"], recommendation: "review-one-or-both", reason: "毛虫画面相同，保留叠词更口语。" },
  { type: "granularity", words: ["小鱼", "鲫鱼"], recommendation: "review-one-or-both", reason: "画鲫鱼只能猜鱼。" },
  { type: "granularity", words: ["老虎", "狮子", "猛兽"], recommendation: "review-one-or-both", reason: "猛兽为上位词，画出来必然是具体猛兽。" },
  { type: "granularity", words: ["虫子", "昆虫"], recommendation: "review-one-or-both", reason: "昆虫上位词，画面必然落到具体虫。" },
  { type: "same-drawing", words: ["麦田", "麦穗", "麦浪", "麦子"], recommendation: "review-one-or-both", reason: "麦作画面重合。" },
  { type: "same-drawing", words: ["稻谷", "粮食", "谷粒"], recommendation: "review-one-or-both", reason: "谷物画面重合。" },
  { type: "same-drawing", words: ["白菜", "萝卜", "蔬菜"], recommendation: "review-one-or-both", reason: "蔬菜上位词与具体菜并存，画面多为具体菜。" },
  { type: "same-drawing", words: ["果园", "果树"], recommendation: "review-one-or-both", reason: "挂果之树画面重合。" },
  { type: "same-drawing", words: ["松树", "雪松", "松针", "松脂"], recommendation: "review-one-or-both", reason: "松树家族画面重合。" },
  { type: "same-drawing", words: ["芦苇", "芦花"], recommendation: "review-one-or-both", reason: "芦花即芦苇之花，画面重合。" },
  { type: "same-drawing", words: ["闹钟", "钟表", "滴答"], recommendation: "review-one-or-both", reason: "钟表滴答画面重合。" },
  { type: "same-drawing", words: ["电视", "广播", "收音机"], recommendation: "review-one-or-both", reason: "影音设备画面相近。" },
  { type: "granularity", words: ["指南针", "方向"], recommendation: "review-one-or-both", reason: "方向箭头与指南针画面可区分但语义近同。" },
  { type: "granularity", words: ["磁铁", "磁场"], recommendation: "review-one-or-both", reason: "磁场示意必然画磁铁。" },
  { type: "same-drawing", words: ["帐篷", "帐子"], recommendation: "review-one-or-both", reason: "床帐帐篷画面相近。" },
  { type: "granularity", words: ["城墙", "墙壁"], recommendation: "review-one-or-both", reason: "砖墙画面重合。" },
  { type: "granularity", words: ["窗户", "窗前"], recommendation: "review-one-or-both", reason: "窗景画面重合。" },
  { type: "granularity", words: ["门", "门板"], recommendation: "review-one-or-both", reason: "门板画面与门重合。" },
  { type: "same-drawing", words: ["中秋赏月", "中秋", "团圆"], recommendation: "review-one-or-both", reason: "中秋团圆场景家族重合。" },
  { type: "same-drawing", words: ["春节贴福", "春节", "过年"], recommendation: "review-one-or-both", reason: "过年场景家族重合。" },
  { type: "same-drawing", words: ["元宵看灯", "花灯", "灯笼"], recommendation: "review-one-or-both", reason: "灯会场景重合。" },
  { type: "same-drawing", words: ["庙会舞狮", "庙会"], recommendation: "review-one-or-both", reason: "庙会场景重合。" },
  { type: "granularity", words: ["红色", "绿色", "黄色", "蓝色", "彩色", "金黄", "翠绿", "墨绿", "碧绿", "嫩绿", "浓绿", "瓦蓝"], recommendation: "review-one-or-both", reason: "色彩家族：深浅色词画面全部落到基础色，新增彩色/金黄等几乎无法区分。" },
  { type: "same-drawing", words: ["发抖", "颤抖", "发颤"], recommendation: "review-one-or-both", reason: "哆嗦画面相同。" },
  { type: "same-drawing", words: ["骄傲", "傲慢", "高傲", "自豪"], recommendation: "review-one-or-both", reason: "昂首得意表情家族。" },
  { type: "same-drawing", words: ["使劲", "用力", "奋力"], recommendation: "review-one-or-both", reason: "用力画面相同。" },
  { type: "same-drawing", words: ["偷偷", "悄悄", "轻声"], recommendation: "review-one-or-both", reason: "蹑手蹑脚画面相同。" },
  { type: "same-drawing", words: ["回忆", "记忆"], recommendation: "review-one-or-both", reason: "回忆泡泡画面相同。" },
  { type: "same-drawing", words: ["朦胧", "模糊", "迷蒙"], recommendation: "review-one-or-both", reason: "模糊视觉效果相同。" },
  { type: "same-drawing", words: ["灰尘", "尘土"], recommendation: "review-one-or-both", reason: "扬尘画面相同。" },
  { type: "same-drawing", words: ["微风", "轻风"], recommendation: "review-one-or-both", reason: "微风拂叶画面相同。" },
  { type: "same-drawing", words: ["盼望", "期待", "希望"], recommendation: "review-one-or-both", reason: "盼望神情画面相同。" },
  { type: "same-drawing", words: ["喜悦", "愉快", "快活"], recommendation: "review-one-or-both", reason: "开心情绪画面相同。" },
  { type: "same-drawing", words: ["忧伤", "悲痛", "沮丧"], recommendation: "review-one-or-both", reason: "悲伤情绪画面相同。" },
  { type: "same-drawing", words: ["害怕", "恐惧", "惊慌", "惊惶"], recommendation: "review-one-or-both", reason: "惊恐表情家族。" },
  { type: "same-drawing", words: ["淘气", "顽皮"], recommendation: "review-one-or-both", reason: "调皮捣蛋画面相同。" },
  { type: "same-drawing", words: ["胆小", "胆怯", "懦弱"], recommendation: "review-one-or-both", reason: "畏缩画面相同。" },
  { type: "same-drawing", words: ["疲倦", "疲劳", "筋疲力尽", "精疲力竭"], recommendation: "review-one-or-both", reason: "疲惫画面家族，横跨双字与四字。" },
  { type: "same-drawing", words: ["遮盖", "遮掩"], recommendation: "review-one-or-both", reason: "遮蔽画面相同。" },
  { type: "same-drawing", words: ["聚集", "聚拢", "汇集"], recommendation: "review-one-or-both", reason: "聚拢画面相同。" },
  { type: "same-drawing", words: ["轮流", "轮换"], recommendation: "review-one-or-both", reason: "轮替画面相同。" },
  { type: "same-drawing", words: ["迷路", "迷失"], recommendation: "review-one-or-both", reason: "迷途画面相同。" },
  { type: "same-drawing", words: ["舒服", "舒适"], recommendation: "review-one-or-both", reason: "惬意瘫坐画面相同。" },
  { type: "same-drawing", words: ["打猎", "猎人"], recommendation: "review-one-or-both", reason: "持械狩猎画面相同，一个是动作一个是人物。" },
  { type: "same-drawing", words: ["欢迎", "迎接"], recommendation: "review-one-or-both", reason: "迎宾画面相同。" },
];
