// 两字词 v1.1 复核决策（第 3 部分：补齐前两部分遗漏的 v1 REVIEW 词）。
export default {
  "中药": { o: "KEEP", d: "normal", t: ["drawable", "culture"], r: "抓药称戥药柜场景进入『中药/草药』邻域，作药材簇代表。" },
  "丰收": { o: "REDUNDANT", c: "收割" },
  "为难": { o: "REVIEW", r: "为难神态与发愁/尴尬画面重合，独立锁定难。" },
  "主人": { o: "REVIEW", r: "角色泛称，画面漂向『主人翁/老板』。" },
  "乖巧": { o: "REVIEW", r: "性格特质词，画面漂向『听话/懂事』。" },
  "光亮": { o: "REDUNDANT", c: "灯" },
  "功夫": { o: "REDUNDANT", c: "武术" },
  "加工": { o: "KEEP", d: "normal", t: ["drawable", "science"], r: "流水线加工/手工作坊场景进入『加工/制作』邻域。" },
  "危险": { o: "KEEP", d: "easy", t: ["drawable", "safety"], r: "警示三角+感叹号符号通用，作当心簇代表，『危险/小心』邻域即命中。" },
  "吃惊": { o: "REDUNDANT", c: "大吃一惊" },
  "呼啸": { o: "REDUNDANT", c: "狂风" },
  "奋力": { o: "REDUNDANT", c: "使劲" },
  "审视": { o: "REDUNDANT", c: "观察" },
  "愉快": { o: "REDUNDANT", c: "快活" },
  "收成": { o: "REDUNDANT", c: "收割" },
  "改变": { o: "REDUNDANT", c: "变化" },
  "放晴": { o: "KEEP", d: "normal", t: ["drawable", "weather"], r: "雨停云开日出瞬间直观，『放晴/天晴了』邻域即命中。" },
  "救命": { o: "REDUNDANT", c: "救援" },
  "整理": { o: "KEEP", d: "normal", t: ["drawable", "home"], r: "归置收纳前后对比直观，『整理/收拾』邻域即命中。" },
  "整齐": { o: "REDUNDANT", c: "排队" },
  "无聊": { o: "REVIEW", r: "百无聊赖神态与发呆画面重合，独立锁定难。" },
  "日本": { o: "REVIEW", r: "依赖国旗符号识别，属地理标志而非画猜。" },
  "早晨": { o: "KEEP", d: "easy", t: ["drawable", "nature"], r: "日出晨练公鸡报晓组合直观，作晨时簇代表，『早晨/早上』邻域即命中。" },
  "昂首": { o: "REDUNDANT", c: "抬头" },
  "昆虫": { o: "REDUNDANT", c: "虫子" },
  "明媚": { o: "REDUNDANT", c: "春天" },
  "明白": { o: "REVIEW", r: "领悟神态是心理/言语概念，画面漂向『懂了/知道』。" },
  "昏暗": { o: "REDUNDANT", c: "黑暗" },
  "春光": { o: "REDUNDANT", c: "春天" },
  "春日": { o: "REDUNDANT", c: "春天" },
  "昼夜": { o: "REVIEW", r: "昼夜对照泛概念，画面漂向『白天黑夜』。" },
  "晃动": { o: "REVIEW", r: "摇晃动作泛义，画面漂向『摇/晃』。" },
  "晌午": { o: "REDUNDANT", c: "早晨" },
  "晚饭": { o: "REDUNDANT", c: "吃饭" },
  "智慧": { o: "REDUNDANT", c: "机灵" },
  "暖和": { o: "REDUNDANT", c: "温暖" },
  "有趣": { o: "REVIEW", r: "评价性泛词，画面漂向『好玩/搞笑』。" },
  "服务": { o: "REVIEW", r: "服务行为泛义，画面漂向『服务员/招待』。" },
  "服装": { o: "REDUNDANT", c: "衣服" },
  "本领": { o: "REVIEW", r: "本领是技能泛称，画面漂向『本事/绝活』。" },
  "桃花": { o: "KEEP", d: "normal", t: ["drawable", "plant"], r: "粉桃满枝春意经典，作花种簇代表（梅花为第二代表），『桃花/桃树』邻域即命中。" },
  "毕业": { o: "KEEP", d: "normal", t: ["drawable", "school"], r: "抛学位帽合影瞬间经典，『毕业/毕业典礼』邻域即命中。" },
  "汽笛": { o: "REVIEW", r: "鸣笛声音词，画面漂向『轮船/喇叭』。" },
  "沉思": { o: "KEEP", d: "normal", t: ["drawable", "action"], r: "思考者托腮姿态经典，『思考/沉思』邻域即命中。" },
  "沉睡": { o: "REDUNDANT", c: "睡觉" },
  "沉重": { o: "REVIEW", r: "重量感受抽象，画面漂向『重/抬不动』。" },
  "沮丧": { o: "REDUNDANT", c: "痛苦" },
  "浓绿": { o: "REDUNDANT", c: "绿色" },
  "满月": { o: "REDUNDANT", c: "月亮" },
  "满载": { o: "REVIEW", r: "装满货物画面漂向『装满/拉货』。" },
  "照顾": { o: "KEEP", d: "normal", t: ["drawable", "action"], r: "喂药掖被照料病幼场景温馨直观，『照顾/照料』邻域即命中。" },
  "父亲": { o: "REDUNDANT", c: "爸爸" },
  "画册": { o: "REDUNDANT", c: "画画" },
  "目送": { o: "KEEP", d: "normal", t: ["drawable", "action"], r: "挥手目送远行构图直观，『目送/送别』邻域即命中。" },
  "碧绿": { o: "REDUNDANT", c: "绿色" },
  "离开": { o: "REVIEW", r: "转身离去画面漂向『走了/出发』，泛义动词。" },
  "翠绿": { o: "REDUNDANT", c: "绿色" },
  "聚拢": { o: "REDUNDANT", c: "聚集" },
  "聚集": { o: "KEEP", d: "normal", t: ["drawable", "action"], r: "人群汇拢画面直观，作聚簇代表，『聚集/围过来』邻域即命中。" },
  "肃静": { o: "REDUNDANT", c: "安静" },
  "肢体": { o: "REVIEW", r: "解剖术语，画面无法指向该词。" },
  "胆小": { o: "KEEP", d: "normal", t: ["drawable", "emotion"], r: "缩脖躲闪形象直观，作怯簇代表，『胆小/害怕』邻域即命中。" },
  "胆怯": { o: "REDUNDANT", c: "胆小" },
  "脱落": { o: "REVIEW", r: "掉落过程泛义，画面漂向『掉了/落叶』。" },
  "自豪": { o: "REDUNDANT", c: "骄傲" },
  "落叶": { o: "REDUNDANT", c: "秋天落叶" },
  "蓝天": { o: "REDUNDANT", c: "天空" },
  "观赏": { o: "REDUNDANT", c: "观察" },
  "记忆": { o: "REDUNDANT", c: "回忆" },
  "讲桌": { o: "REDUNDANT", c: "老师讲课" },
  "访问": { o: "REDUNDANT", c: "采访" },
  "踪迹": { o: "REDUNDANT", c: "痕迹" },
  "轮换": { o: "REDUNDANT", c: "轮流" },
  "轮流": { o: "KEEP", d: "normal", t: ["drawable", "action"], r: "依次交替+循环箭头直观，作轮簇代表，『轮流/一个接一个』邻域即命中。" },
  "轰鸣": { o: "REVIEW", r: "声音状态词，画面漂向『很吵/发动机』。" },
  "轻声": { o: "REDUNDANT", c: "偷偷" },
  "轻快": { o: "REVIEW", r: "轻快步态与轻巧/活泼画面重合。" },
  "轻风": { o: "REDUNDANT", c: "微风" },
  "辛酸": { o: "REVIEW", r: "辛酸心境沉重抽象，交人工判断。" },
  "连续": { o: "REVIEW", r: "接连关系抽象，画面漂向『一个接一个』。" },
  "迷失": { o: "REDUNDANT", c: "迷路" },
  "迷蒙": { o: "REDUNDANT", c: "模糊" },
  "道路": { o: "REDUNDANT", c: "马路" },
  "铃声": { o: "REDUNDANT", c: "铃铛" },
  "隐蔽": { o: "REDUNDANT", c: "捉迷藏" },
  "黄河": { o: "REVIEW", r: "依赖地理标识，画面漂向『河/壶口瀑布』。" },
};
