// 两字词 v1.1 复核决策（第 2/2 部分：v1 决策后段的 REVIEW 项与 KEEP 调整）。
export default {
  // —— KEEP 调整（v1 KEEP → v1.1 其它终态）——
  "坦克": { o: "REVIEW", r: "军用武器平台，画面清晰但武器属性强，按 v1.1 硬拒绝复查交人工判断（词库已有军舰先例）。" },
  "猎人": { o: "REVIEW", r: "持枪牵犬狩猎含暴力指向，画面清晰不构成保留理由，交人工判断。" },
  "结婚": { o: "REDUNDANT", c: "新娘" },
  "春节": { o: "REDUNDANT", c: "过年" },

  // —— 后段 REVIEW 的 v1.1 复核 ——
  "人类": { o: "REVIEW", r: "泛指全体人类，画面漂向『人们/人群』，独立成题弱。" },
  "仇人": { o: "REVIEW", r: "怒目相向含敌对冲突，负面程度交人工判断。" },
  "停泊": { o: "KEEP", d: "normal", t: ["drawable", "transport"], r: "船只靠岸停驻画面直观，『停泊/停靠』邻域即命中。" },
  "倒映": { o: "REDUNDANT", c: "倒影" },
  "修建": { o: "REDUNDANT", c: "高楼" },
  "修筑": { o: "REDUNDANT", c: "高楼" },
  "修补": { o: "REVIEW", r: "缝补衣物画面漂向『缝衣服/补衣服』，独立成题弱。" },
  "倾听": { o: "KEEP", d: "normal", t: ["drawable", "action"], r: "拢耳侧听手势直观，『倾听/侧耳听』邻域即命中。" },
  "准备": { o: "REVIEW", r: "收拾行装画面漂向『收拾/打包』，泛义动词独立成题弱。" },
  "创造": { o: "REDUNDANT", c: "发明" },
  "动物": { o: "REVIEW", r: "上位词游戏体验特殊：画任何动物都会被猜成具体动物名，是否保留泛词交产品判断。" },
  "助威": { o: "KEEP", d: "normal", t: ["drawable", "sports"], r: "场边摇旗呐喊加油场景热烈，『加油/助威』邻域即命中。" },
  "努力": { o: "KEEP", d: "normal", t: ["drawable", "school"], r: "灯下苦读/加练画面进入『用功/努力』邻域。" },
  "劳动": { o: "KEEP", d: "normal", t: ["drawable", "action"], r: "打扫干活场景直观，『干活/劳动』邻域即命中。" },
  "勇气": { o: "KEEP", d: "normal", t: ["drawable", "emotion"], r: "挺身而出瞬间进入『勇敢/勇气』邻域。" },
  "勇猛": { o: "REVIEW", r: "冲锋猛打形象偏战斗暴力，交人工判断家庭适配性。" },
  "可怜": { o: "REVIEW", r: "楚楚可怜神态与伤心/同情难以区分出独立体验。" },
  "双臂": { o: "REDUNDANT", c: "胳膊" },
  "反抗": { o: "REVIEW", r: "推挡对抗画面含冲突，负面程度交人工判断。" },
  "后悔": { o: "KEEP", d: "normal", t: ["drawable", "emotion"], r: "拍头懊恼神态有戏剧性，『后悔/懊悔』邻域即命中。" },
  "向导": { o: "KEEP", d: "normal", t: ["drawable", "person"], r: "举旗带队形象明确，『向导/导游』邻域即命中。" },
  "吓唬": { o: "KEEP", d: "normal", t: ["drawable", "action"], r: "躲门后跳出惊吓的恶作剧场景滑稽，『吓唬/吓一跳』邻域命中。" },
  "呐喊": { o: "REDUNDANT", c: "助威" },
  "垂柳": { o: "REDUNDANT", c: "柳树" },
  "垫子": { o: "KEEP", d: "easy", t: ["drawable", "object"], r: "坐垫蒲团直观，『垫子/坐垫』邻域即命中。" },
  "埋头": { o: "KEEP", d: "normal", t: ["drawable", "action"], r: "伏案埋头姿态明确，『埋头/低头写』邻域命中。" },
  "培养": { o: "REVIEW", r: "浇花育苗画面漂向『浇水/种花』，抽象动词独立成题弱。" },
  "基地": { o: "REVIEW", r: "泛称场地，画面漂向『营地/军事基地』，语义不确定。" },
  "堆积": { o: "KEEP", d: "normal", t: ["drawable", "action"], r: "货物成山画面直观，『堆成山/堆积』邻域即命中。" },
  "增加": { o: "KEEP", d: "normal", t: ["drawable"], r: "由少变多对比+上升箭头直观，『变多/增加』邻域命中。" },
  "墨绿": { o: "REDUNDANT", c: "绿色" },
  "复活": { o: "KEEP", d: "hard", t: ["drawable", "science"], r: "化石复生/机器人重启的奇幻场景有趣，『活了/复活』邻域命中。" },
  "外宾": { o: "REVIEW", r: "外宾迎宾场景偏正式外交，儿童作题价值存疑。" },
  "嫂子": { o: "REVIEW", r: "亲属称谓画面无从区分锁定，且无更常用代表词可挂靠。" },
  "嫩红": { o: "REDUNDANT", c: "红色" },
  "嫩绿": { o: "REDUNDANT", c: "绿色" },
  "悄悄": { o: "REDUNDANT", c: "偷偷" },
  "抛弃": { o: "REVIEW", r: "丢弃离去场景偏负面（遗弃感），基调交人工判断。" },
  "抱怨": { o: "KEEP", d: "normal", t: ["drawable", "emotion"], r: "撇嘴唠叨神态生动，『抱怨/埋怨』邻域即命中。" },
  "拆除": { o: "KEEP", d: "normal", t: ["drawable", "action"], r: "敲墙拆楼/挖掘机作业画面直观，『拆/拆除』邻域即命中。" },
  "攻击": { o: "REJECT", r: "进攻攻击为直接暴力内容，与家庭游戏氛围不符。" },
  "研究": { o: "REDUNDANT", c: "实验" },
  "砸锅": { o: "REVIEW", r: "摔锅画面奇特但近乎无厘头，儿童理解『砸锅卖铁』语境的少。" },
  "磁场": { o: "REDUNDANT", c: "磁铁" },
  "示意": { o: "REVIEW", r: "手势指向语义宽泛，画面无法锁定。" },
  "礼貌": { o: "KEEP", d: "normal", t: ["drawable", "culture"], r: "鞠躬问好/让座姿态直观，『有礼貌/问好』邻域命中。" },
  "祖先": { o: "REVIEW", r: "祖先牌位族谱场景肃穆沉重，交人工判断。" },
  "神气": { o: "REDUNDANT", c: "骄傲" },
  "神秘": { o: "REDUNDANT", c: "秘密" },
  "秘密": { o: "KEEP", d: "normal", t: ["drawable", "emotion"], r: "附耳密语/藏宝盒画面直观，作神秘簇代表，『悄悄话/秘密』邻域命中。" },
  "禾苗": { o: "REDUNDANT", c: "麦苗" },
  "秩序": { o: "REDUNDANT", c: "排队" },
  "积雪": { o: "REDUNDANT", c: "雪山" },
  "称赞": { o: "REDUNDANT", c: "夸奖" },
  "移动": { o: "REVIEW", r: "泛义移动动词，画面漂向『挪/搬』。" },
  "空隙": { o: "REDUNDANT", c: "缝隙" },
  "缝隙": { o: "KEEP", d: "normal", t: ["drawable"], r: "门缝墙裂特写直观，作间隙簇代表，『缝/缝隙』邻域即命中。" },
  "穿戴": { o: "REDUNDANT", c: "打扮" },
  "窗前": { o: "REDUNDANT", c: "窗户" },
  "窟窿": { o: "REDUNDANT", c: "山洞" },
  "童年": { o: "KEEP", d: "normal", t: ["drawable", "emotion"], r: "孩提玩趣/老照片画面进入『小时候/童年』邻域。" },
  "童话": { o: "KEEP", d: "normal", t: ["drawable", "culture"], r: "城堡巨龙翻开的巨书进入『童话故事』邻域。" },
  "笑话": { o: "KEEP", d: "normal", t: ["drawable", "emotion"], r: "捧腹讲笑场景滑稽，『讲笑话/搞笑』邻域命中。" },
  "笨拙": { o: "REDUNDANT", c: "笨重" },
  "笨重": { o: "KEEP", d: "normal", t: ["drawable"], r: "庞然大物挪动迟缓画面直观，作笨簇代表，『笨重/沉』邻域即命中。" },
  "笼罩": { o: "REVIEW", r: "烟雾笼罩氛围词，画面漂向『弥漫/包围』。" },
  "等待": { o: "KEEP", d: "normal", t: ["drawable", "action"], r: "守候张望+时钟画面直观，『等/等待』邻域即命中。" },
  "答应": { o: "KEEP", d: "normal", t: ["drawable", "action"], r: "点头应允神态明确，『同意/答应』邻域即命中。" },
  "簇拥": { o: "REDUNDANT", c: "聚集" },
  "粉刷": { o: "KEEP", d: "normal", t: ["drawable", "action"], r: "滚筒刷墙画面直观，『刷墙/粉刷』邻域即命中。" },
  "粗壮": { o: "REVIEW", r: "粗大质感形容词，画面漂向『粗/壮』。" },
  "粮食": { o: "REDUNDANT", c: "稻谷" },
  "糕饼": { o: "REDUNDANT", c: "蛋糕" },
  "糟糕": { o: "KEEP", d: "normal", t: ["drawable", "emotion"], r: "捂头懊恼+打翻场景滑稽，『糟糕/坏了』邻域即命中。" },
  "紧急": { o: "KEEP", d: "normal", t: ["drawable", "safety"], r: "警报红灯+疾奔画面有紧迫感，『紧急/危急』邻域命中。" },
  "繁忙": { o: "REDUNDANT", c: "忙碌" },
  "繁星": { o: "REDUNDANT", c: "星空" },
  "繁殖": { o: "REVIEW", r: "生物繁衍科普图示，作题体验偏课堂。" },
  "红晕": { o: "REDUNDANT", c: "难为情" },
  "红烧": { o: "REDUNDANT", c: "美食" },
  "纪念": { o: "REDUNDANT", c: "纪念碑" },
  "线条": { o: "REVIEW", r: "抽象构图元素，画面即若干线，无从猜起。" },
  "细胞": { o: "REVIEW", r: "显微镜示意图偏科普图鉴，独立作题价值交人工判断。" },
  "绒毛": { o: "REDUNDANT", c: "毛茸茸" },
  "结实": { o: "REVIEW", r: "结实（牢固）与结果实双关，画面语义不确定。" },
  "绝望": { o: "REVIEW", r: "绝望情绪基调沉重，交人工判断。" },
  "绝活": { o: "KEEP", d: "hard", t: ["drawable", "culture"], r: "杂技绝技表演场景精彩，『绝活/拿手绝技』邻域命中。" },
  "继续": { o: "REVIEW", r: "接续关系抽象，画面漂向『接着/再来』。" },
  "绸子": { o: "REDUNDANT", c: "布料" },
  "绿毯": { o: "REDUNDANT", c: "草地" },
  "编织": { o: "KEEP", d: "normal", t: ["drawable", "home"], r: "织毛衣编篮场景温馨直观，『织/编织』邻域即命中。" },
  "羊肉": { o: "REVIEW", r: "肉类食材画面漂向『肉/羊肉串』，独立成题弱。" },
  "美餐": { o: "REDUNDANT", c: "美食" },
  "群星": { o: "REDUNDANT", c: "星空" },
  "翻身": { o: "KEEP", d: "normal", t: ["drawable", "action"], r: "翻身打滚动作明确，『翻身/打滚』邻域即命中。" },
  "考察": { o: "REDUNDANT", c: "探险" },
  "耐心": { o: "REVIEW", r: "耐心守候与安静/坚持画面重合，独立锁定难。" },
  "肥料": { o: "REVIEW", r: "农资物品儿童陌生，画面漂向『施肥/化肥袋』。" },
  "背包": { o: "REDUNDANT", c: "书包" },
  "胳膊": { o: "KEEP", d: "easy", t: ["drawable", "body"], r: "屈臂展示/挥臂动作直观，作臂簇代表，『胳膊/手臂』邻域即命中。" },
  "胸膛": { o: "KEEP", d: "normal", t: ["drawable", "body"], r: "挺胸昂首姿态直观，『胸膛/胸口』邻域命中。" },
  "能源": { o: "REDUNDANT", c: "发电站" },
  "脊背": { o: "REVIEW", r: "背部特写画面漂向『后背/背影』，独立成题弱。" },
  "脚尖": { o: "KEEP", d: "normal", t: ["drawable", "body"], r: "踮脚尖芭蕾姿态直观，『踮脚/脚尖』邻域即命中。" },
  "脚步": { o: "REDUNDANT", c: "雪地脚印" },
  "脚跟": { o: "REVIEW", r: "身体局部特写难以独立成题。" },
  "脸颊": { o: "KEEP", d: "easy", t: ["drawable", "body"], r: "红扑扑脸蛋特写直观，『脸蛋/脸颊』邻域即命中。" },
  "脾气": { o: "KEEP", d: "normal", t: ["drawable", "emotion"], r: "怒气冲冲摔门场景滑稽，『发脾气/脾气』邻域即命中。" },
  "膨大": { o: "REVIEW", r: "膨胀变形画面漂向『变大/膨胀』，书面词。" },
  "自信": { o: "KEEP", d: "normal", t: ["drawable", "emotion"], r: "昂首亮相姿态直观，『自信/有信心』邻域命中。" },
  "自然": { o: "KEEP", d: "normal", t: ["drawable", "nature"], r: "山水草木原野画面进入『大自然/自然界』邻域，作代表词。" },
  "自由": { o: "KEEP", d: "normal", t: ["drawable", "emotion"], r: "开笼放飞/奔跑张开双臂进入『自由』邻域。" },
  "舅父": { o: "REDUNDANT", c: "叔叔" },
  "舒服": { o: "KEEP", d: "easy", t: ["drawable", "emotion"], r: "瘫坐惬意的姿态直观，作舒适簇代表，『舒服/舒适』邻域即命中。" },
  "舒适": { o: "REDUNDANT", c: "舒服" },
  "舞蹈": { o: "REDUNDANT", c: "跳舞" },
  "船夫": { o: "REDUNDANT", c: "划船" },
  "船头": { o: "REVIEW", r: "船的局部，画面漂向『船』，独立成题弱。" },
  "船舱": { o: "REVIEW", r: "船的局部舱室，画面漂向『船里』。" },
  "船队": { o: "REVIEW", r: "船群画面漂向『许多船/舰队』，独立成题弱。" },
  "艰难": { o: "REDUNDANT", c: "困难" },
  "艳丽": { o: "REDUNDANT", c: "彩虹" },
  "节拍": { o: "REVIEW", r: "音乐节拍抽象，画面漂向『打拍子/节奏』。" },
  "节日": { o: "REDUNDANT", c: "庆祝" },
  "节省": { o: "REVIEW", r: "省钱存钱场景偏说教，交人工判断。" },
  "芝麻": { o: "REVIEW", r: "颗粒细小难以独立成画，画面漂向『小种子』。" },
  "芦花": { o: "REDUNDANT", c: "芦苇" },
  "芬芳": { o: "REDUNDANT", c: "香味" },
  "花丛": { o: "REDUNDANT", c: "花朵" },
  "花灯": { o: "REDUNDANT", c: "灯笼" },
  "花纹": { o: "KEEP", d: "normal", t: ["drawable", "color"], r: "瓷器布面纹样特写直观，『花纹/图案』邻域即命中。" },
  "花蕾": { o: "REDUNDANT", c: "花骨朵儿" },
  "苍白": { o: "REVIEW", r: "病容气色词，画面漂向『生病/没血色』，基调偏负面。" },
  "苍翠": { o: "REDUNDANT", c: "绿色" },
  "苍耳": { o: "REVIEW", r: "植物物种儿童陌生，画面难以识别。" },
  "苏醒": { o: "REDUNDANT", c: "醒来" },
  "苔藓": { o: "REVIEW", r: "苔藓质感儿童难以识别命名。" },
  "茂盛": { o: "REDUNDANT", c: "森林" },
  "茅屋": { o: "KEEP", d: "normal", t: ["drawable", "place"], r: "稻草屋顶小屋造型独特（三只小猪意象），『茅屋/草屋』邻域命中。" },
  "草丛": { o: "REDUNDANT", c: "草地" },
  "草坪": { o: "REDUNDANT", c: "草地" },
  "草堆": { o: "REVIEW", r: "草垛画面漂向『干草/草垛』，农村意象儿童渐陌生。" },
  "草籽": { o: "REVIEW", r: "细小种子难以独立成画。" },
  "荒凉": { o: "REDUNDANT", c: "荒漠" },
  "荒野": { o: "REDUNDANT", c: "野外" },
  "荡漾": { o: "REDUNDANT", c: "波纹" },
  "药材": { o: "REDUNDANT", c: "中药" },
  "藤萝": { o: "REVIEW", r: "紫藤植物名儿童陌生，画面漂向『藤/花架』。" },
  "血液": { o: "REVIEW", r: "血的画面偏医学敏感，交人工判断。" },
  "行驶": { o: "REDUNDANT", c: "汽车" },
  "街道": { o: "REDUNDANT", c: "马路" },
  "衣裳": { o: "REDUNDANT", c: "衣服" },
  "袖子": { o: "REVIEW", r: "服装局部，画面漂向『挽袖子』，独立成题弱。" },
  "装饰": { o: "REDUNDANT", c: "布置" },
  "角色": { o: "REVIEW", r: "元概念词，画面漂向『扮演/演戏』。" },
  "角落": { o: "KEEP", d: "normal", t: ["drawable", "place"], r: "墙角旮旯/罚站小孩画面直观，『角落/墙角』邻域即命中。" },
  "解决": { o: "KEEP", d: "normal", t: ["drawable", "action"], r: "解绳团/通关打勾画面直观，『解决/搞定』邻域即命中。" },
  "解闷": { o: "REVIEW", r: "逗乐解闷画面漂向『逗笑/玩』，独立成题弱。" },
  "触角": { o: "REVIEW", r: "蜗牛触角特写偏科普局部，独立成题弱。" },
  "警戒": { o: "KEEP", d: "normal", t: ["drawable", "safety"], r: "警戒线/哨兵拦阻画面明确，『警戒线/警戒』邻域命中。" },
  "警觉": { o: "REVIEW", r: "警觉状态与警戒/注意画面重合，独立锁定难。" },
  "认真": { o: "KEEP", d: "normal", t: ["drawable", "school"], r: "专注书写一丝不苟画面直观，作专心簇代表（含四字全神贯注），『认真/专心』邻域命中。" },
  "记录": { o: "KEEP", d: "normal", t: ["drawable", "school"], r: "持板速记画面直观，『记录/记笔记』邻域即命中。" },
  "讲座": { o: "REDUNDANT", c: "老师讲课" },
  "设计": { o: "REDUNDANT", c: "绘图" },
  "证据": { o: "KEEP", d: "normal", t: ["drawable", "safety"], r: "放大镜+线索拼图画面有侦探趣味，『证据/线索』邻域命中。" },
  "请求": { o: "KEEP", d: "normal", t: ["drawable", "action"], r: "恳切合掌姿态明确，作恳求簇代表，『请求/恳求』邻域即命中。" },
  "央求": { o: "REDUNDANT", c: "请求" },
  "谎话": { o: "KEEP", d: "normal", t: ["drawable", "emotion"], r: "匹诺曹长鼻画面经典，『撒谎/谎话』邻域即命中。" },
  "谷粒": { o: "REDUNDANT", c: "稻谷" },
  "贺年": { o: "REDUNDANT", c: "过年" },
  "赛跑": { o: "REDUNDANT", c: "跑步" },
  "赞叹": { o: "REDUNDANT", c: "夸奖" },
  "赞许": { o: "REDUNDANT", c: "夸奖" },
  "赶紧": { o: "REDUNDANT", c: "急急忙忙" },
  "赶集": { o: "REVIEW", r: "乡集场景乡土气息浓，当代儿童熟悉度下降，交人工判断。" },
  "超过": { o: "REVIEW", r: "反超瞬间画面漂向『超车/第一名』，比较关系抽象。" },
  "跳动": { o: "REVIEW", r: "跳动脉动画面漂向『心脏/跳』。" },
  "踏步": { o: "REVIEW", r: "原地踏步与踏/走画面重合，独立成题弱。" },
  "辽阔": { o: "REDUNDANT", c: "宽阔" },
  "迅速": { o: "KEEP", d: "normal", t: ["drawable", "sports"], r: "速度线疾冲画面直观，作敏捷簇代表，『快/迅速』邻域即命中。" },
  "敏捷": { o: "REDUNDANT", c: "迅速" },
  "过冬": { o: "KEEP", d: "normal", t: ["drawable", "animal"], r: "松鼠储粮/熊冬眠场景可爱，『过冬/冬眠』邻域即命中。" },
  "迎接": { o: "REDUNDANT", c: "欢迎" },
  "迟钝": { o: "REDUNDANT", c: "慢吞吞" },
  "迷惑": { o: "REDUNDANT", c: "疑问" },
  "追逐": { o: "KEEP", d: "normal", t: ["drawable", "action"], r: "你追我赶场景动感强，『追/追逐』邻域即命中。" },
  "退缩": { o: "REDUNDANT", c: "后退" },
  "选择": { o: "REVIEW", r: "岔路抉择画面偏抽象概念（决定本身），交人工判断。" },
  "透明": { o: "REVIEW", r: "材质性质词，画面依赖玻璃水母等载体，独立成题弱。" },
  "逗引": { o: "REVIEW", r: "逗弄引逗画面漂向『逗/引诱』，独立成题弱。" },
  "避免": { o: "REVIEW", r: "闪避概念抽象，画面漂向『躲开』。" },
  "郊外": { o: "REDUNDANT", c: "野外" },
  "配合": { o: "REDUNDANT", c: "合力" },
  "酷暑": { o: "REDUNDANT", c: "炎热" },
  "醒来": { o: "KEEP", d: "normal", t: ["drawable", "action"], r: "睡醒睁眼伸懒腰画面直观，作苏醒簇代表，『醒来/睡醒』邻域即命中。" },
  "重叠": { o: "REVIEW", r: "层层叠加偏构图概念，画面漂向『叠起来』。" },
  "野兔": { o: "REDUNDANT", c: "兔子" },
  "野外": { o: "KEEP", d: "normal", t: ["drawable", "nature"], r: "原野露营烧烤场景直观，作郊外簇代表，『野外/郊外』邻域即命中。" },
  "野果": { o: "REDUNDANT", c: "果园" },
  "野花": { o: "REDUNDANT", c: "花朵" },
  "野鸭": { o: "REDUNDANT", c: "鸭子" },
  "金黄": { o: "REDUNDANT", c: "黄色" },
  "钓竿": { o: "REDUNDANT", c: "钓鱼" },
  "钢铁": { o: "REVIEW", r: "材料泛称，画面漂向『钢筋/金属』，独立成题弱。" },
  "钱币": { o: "REDUNDANT", c: "铜钱" },
  "锋利": { o: "REVIEW", r: "刀刃寒光画面漂向『尖/快』，且带刀具意象。" },
  "锻炼": { o: "REDUNDANT", c: "跑步" },
  "长江": { o: "REVIEW", r: "依赖地图地理标识，画面漂向『大河/江』。" },
  "门板": { o: "REDUNDANT", c: "门" },
  "闪烁": { o: "REDUNDANT", c: "闪闪发光" },
  "闲散": { o: "REVIEW", r: "闲散状态与悠闲画面重合，书面词。" },
  "间隔": { o: "REDUNDANT", c: "缝隙" },
  "防御": { o: "KEEP", d: "normal", t: ["drawable", "action"], r: "盾墙防守/球门扑救画面直观，作抵御簇代表，『防御/防守』邻域即命中。" },
  "抵御": { o: "REDUNDANT", c: "防御" },
  "阴冷": { o: "REVIEW", r: "阴冷氛围与阴暗/寒冷画面重合，独立锁定难。" },
  "阴暗": { o: "REDUNDANT", c: "黑暗" },
  "阵雨": { o: "REDUNDANT", c: "暴风雨" },
  "陆地": { o: "REVIEW", r: "海陆对照画面漂向『地面/大地』，地理概念独立成题弱。" },
  "陆续": { o: "REVIEW", r: "先后到来是关系描述，画面漂向『一个接一个』。" },
  "陌生": { o: "REVIEW", r: "生疏感受抽象，画面漂向『不认识/第一次见』。" },
  "降临": { o: "REVIEW", r: "来临是抽象动词，画面漂向『夜幕降临/到来』。" },
  "院墙": { o: "REDUNDANT", c: "墙壁" },
  "陶醉": { o: "REVIEW", r: "沉醉神态与享受画面重合，独立锁定难。" },
  "隐形": { o: "KEEP", d: "normal", t: ["drawable", "science"], r: "虚影半透明人形画面有趣，『隐形/隐身』邻域即命中。" },
  "难堪": { o: "REDUNDANT", c: "难为情" },
  "雄伟": { o: "REDUNDANT", c: "壮观" },
  "集中": { o: "REDUNDANT", c: "聚集" },
  "雨滴": { o: "REDUNDANT", c: "雨点" },
  "雨点": { o: "KEEP", d: "easy", t: ["drawable", "weather"], r: "雨点纷落特写直观，作雨珠簇代表，『雨点/下雨』邻域即命中。" },
  "雨珠": { o: "REDUNDANT", c: "雨点" },
  "雨露": { o: "REVIEW", r: "雨露 poetic 意象，画面漂向『露珠/下雨』。" },
  "雪松": { o: "REDUNDANT", c: "松树" },
  "雷声": { o: "REDUNDANT", c: "雷雨" },
  "雹子": { o: "REDUNDANT", c: "冰雹" },
  "露水": { o: "REDUNDANT", c: "露珠" },
  "靠岸": { o: "REDUNDANT", c: "轮船靠岸" },
  "项圈": { o: "REVIEW", r: "项圈画面漂向『项链/宠物圈』，独立成题弱。" },
  "顺序": { o: "REDUNDANT", c: "排队" },
  "顽皮": { o: "REDUNDANT", c: "淘气" },
  "预告": { o: "REDUNDANT", c: "预报" },
  "预报": { o: "KEEP", d: "normal", t: ["drawable", "science"], r: "天气预报播报地图画面直观，作预告簇代表，『天气预报/预报』邻域命中。" },
  "额角": { o: "REVIEW", r: "身体局部特写，独立成题弱。" },
  "颤抖": { o: "REDUNDANT", c: "发抖" },
  "风俗": { o: "REVIEW", r: "民俗风情泛称，画面无法锁定。" },
  "风景": { o: "KEEP", d: "normal", t: ["drawable", "nature"], r: "湖光山色画面经典，作景色簇代表，『风景/景色』邻域即命中。" },
  "景色": { o: "REDUNDANT", c: "风景" },
  "风暴": { o: "REDUNDANT", c: "暴风雨" },
  "飘动": { o: "REDUNDANT", c: "飘浮" },
  "飘浮": { o: "KEEP", d: "normal", t: ["drawable", "science"], r: "悬浮半空画面直观，作浮簇代表，『飘/浮起来』邻域即命中。" },
  "飞舞": { o: "REDUNDANT", c: "蝴蝶飞舞" },
  "飞越": { o: "REVIEW", r: "飞越动作依附载体，画面漂向『飞过/跳过』。" },
  "飞驰": { o: "REDUNDANT", c: "赛车" },
  "饭菜": { o: "REDUNDANT", c: "吃饭" },
  "饭馆": { o: "REDUNDANT", c: "餐厅" },
  "香甜": { o: "REDUNDANT", c: "香味" },
  "马蹄": { o: "REVIEW", r: "马的局部，画面漂向『马蹄铁/奔跑』。" },
  "骄傲": { o: "KEEP", d: "normal", t: ["drawable", "emotion"], r: "昂首挺胸翘下巴神态经典，作傲簇代表，『骄傲/得意』邻域即命中（v1 因词面歧义压级，v1.1 修正）。" },
  "骏马": { o: "REDUNDANT", c: "骑马" },
  "高傲": { o: "REDUNDANT", c: "骄傲" },
  "鲜美": { o: "REDUNDANT", c: "美食" },
  "鲜艳": { o: "REDUNDANT", c: "彩虹" },
  "鲜花": { o: "REDUNDANT", c: "花朵" },
  "鲫鱼": { o: "REDUNDANT", c: "小鱼" },
  "麦子": { o: "REDUNDANT", c: "麦田" },
  "麻烦": { o: "REVIEW", r: "麻烦是泛义状态词，画面漂向『乱/糟糕』。" },
  "黄昏": { o: "KEEP", d: "normal", t: ["drawable", "nature"], r: "夕阳西下剪影经典，作暮簇代表，『黄昏/傍晚』邻域即命中。" },
  "黎明": { o: "REDUNDANT", c: "黄昏" },
  "黑夜": { o: "REDUNDANT", c: "夜晚" },
  "黑暗": { o: "KEEP", d: "normal", t: ["drawable", "nature"], r: "无光环境画面直观，作暗簇代表，『黑暗/一片黑』邻域即命中。" },
  "鼓点": { o: "REDUNDANT", c: "打鼓" },
  "龟裂": { o: "REVIEW", r: "书面词（jūnliè），龟裂土地画面儿童难命名。" },
  "乌黑": { o: "REDUNDANT", c: "黑暗" },
  "枯萎": { o: "KEEP", d: "normal", t: ["drawable", "plant"], r: "蔫萎下垂的花草画面直观，『枯萎/蔫了』邻域即命中。" },
  "染缸": { o: "REVIEW", r: "染布大缸旧式作坊，儿童陌生。" },
  "柳叶": { o: "REDUNDANT", c: "柳树" },
  "柳枝": { o: "REDUNDANT", c: "柳树" },
  "清静": { o: "REDUNDANT", c: "安静" },
  "牲畜": { o: "REDUNDANT", c: "农场" },
  "狂吠": { o: "KEEP", d: "normal", t: ["drawable", "animal"], r: "犬吠扑跳画面生动，『狗叫/狂吠』邻域即命中。" },
  "狂欢": { o: "REDUNDANT", c: "庆祝" },
  "狂风": { o: "KEEP", d: "normal", t: ["drawable", "weather"], r: "树倒物飞的大风画面有冲击力，作呼啸簇代表，『大风/狂风』邻域即命中。" },
  "狭窄": { o: "REVIEW", r: "空间属性词，画面漂向『窄/小巷』。" },
  "猎物": { o: "REVIEW", r: "猎获场景含狩猎暴力指向，随打猎/猎人一并交人工判断。" },
  "猛兽": { o: "REDUNDANT", c: "老虎" },
  "王朝": { o: "REVIEW", r: "朝代概念抽象，画面漂向『皇宫/古代』。" },
  "玻璃": { o: "REVIEW", r: "透明材质难以在画中独立识别。" },
  "珍宝": { o: "REDUNDANT", c: "宝石" },
  "琴键": { o: "REDUNDANT", c: "钢琴" },
  "瓦蓝": { o: "REDUNDANT", c: "蓝色" },
  "甜菜": { o: "REDUNDANT", c: "萝卜" },
  "甜蜜": { o: "REVIEW", r: "甜蜜氛围词，画面漂向『甜/幸福』。" },
  "生物": { o: "REVIEW", r: "泛指生命体，画面漂向『动物/虫子』，上位词交产品判断。" },
  "生长": { o: "KEEP", d: "normal", t: ["drawable", "plant"], r: "破土拔节生长序列画面直观，『长大/生长』邻域即命中。" },
  "用力": { o: "REDUNDANT", c: "使劲" },
  "男孩": { o: "REDUNDANT", c: "弟弟" },
  "表弟": { o: "REDUNDANT", c: "弟弟" },
  "表演": { o: "REDUNDANT", c: "演员" },
  "陷坑": { o: "REVIEW", r: "陷阱深坑画面漂向『陷阱/坑』，且略带伤害意味。" },
  "旗帜": { o: "REDUNDANT", c: "国旗" },
  "水泥": { o: "REVIEW", r: "建材灰浆儿童陌生，画面难以独立识别。" },
  "机器": { o: "REDUNDANT", c: "机器人" },
  "机械": { o: "REDUNDANT", c: "齿轮" },
  "晶莹": { o: "REDUNDANT", c: "闪闪发光" },
  "严寒": { o: "REDUNDANT", c: "冬天" },
  "亲密": { o: "REDUNDANT", c: "拥抱" },
  "形状": { o: "KEEP", d: "normal", t: ["drawable", "color"], r: "几何图形组合直观，『形状/图形』邻域即命中。" },
  "遮盖": { o: "KEEP", d: "normal", t: ["drawable", "action"], r: "布幔盖物动作明确，作遮簇代表，『盖住/遮盖』邻域即命中。" },
  "遮掩": { o: "REDUNDANT", c: "遮盖" },
  "成功": { o: "REDUNDANT", c: "胜利" },
  "叹气": { o: "KEEP", d: "normal", t: ["drawable", "emotion"], r: "垂头长叹画面直观，作叹簇代表，『叹气/叹了口气』邻域即命中。" },
  "叹息": { o: "REDUNDANT", c: "叹气" },
  "抖动": { o: "REDUNDANT", c: "发抖" },
};
