// 两字词 v1.1 复核决策（第 1/2 部分，对应 v1 决策前半段的 REVIEW 与 KEEP 调整）。
// o: KEEP（附 d/t/r）| REJECT（附 r）| REVIEW（附 r）| REDUNDANT（附 c=代表词）。
// 未在本系列文件出现的 v1-REVIEW 词视为遗漏，构建脚本会报错。
export default {
  "丁零": { o: "REVIEW", r: "拟声词，画面只能落到铃铛本体，作题略显单薄。" },
  "上升": { o: "KEEP", d: "normal", t: ["drawable", "action"], r: "气球升空/电梯上行方向感明确，『升/升空』邻域直达。" },
  "下降": { o: "KEEP", d: "normal", t: ["drawable", "action"], r: "下落/降落画面直观，与上升成对，『降/落下』邻域可达。" },
  "不安": { o: "REDUNDANT", c: "担心" },
  "不屈": { o: "REVIEW", r: "精神品质词，可用倔强姿态暗示，但是否适合轻松游戏需人工判断。" },
  "专家": { o: "KEEP", d: "normal", t: ["drawable", "person"], r: "讲台学者形象进入『教授/博士』邻域即命中。" },
  "世界": { o: "KEEP", d: "normal", t: ["drawable", "place"], r: "地球仪/环球画面进入『地球/全世界』邻域。" },
  "东北": { o: "REVIEW", r: "依赖地图方位表达，儿童作画难度大。" },
  "严厉": { o: "REDUNDANT", c: "严肃" },
  "严肃": { o: "KEEP", d: "normal", t: ["drawable", "emotion"], r: "板着脸的表情明确，『严肃/认真脸』邻域命中，作严肃簇代表。" },
  "传说": { o: "KEEP", d: "normal", t: ["drawable", "culture"], r: "老者讲古场景进入『讲故事』邻域。" },
  "伯伯": { o: "REDUNDANT", c: "叔叔" },
  "伏案": { o: "REVIEW", r: "书面词，画面只能落到趴桌写字，儿童熟悉度不足。" },
  "休息": { o: "KEEP", d: "easy", t: ["drawable", "action"], r: "躺椅小憩直观，『歇会/休息』邻域即命中。" },
  "乐器": { o: "KEEP", d: "normal", t: ["drawable", "object"], r: "多件乐器陈列画面进入『乐器/演奏』邻域。" },
  "云彩": { o: "REDUNDANT", c: "白云" },
  "交叉": { o: "KEEP", d: "normal", t: ["drawable"], r: "双臂交叉/道路十字直观，『交叉/十字』邻域命中。" },
  "亮光": { o: "REDUNDANT", c: "灯" },
  "倒霉": { o: "KEEP", d: "normal", t: ["drawable", "emotion"], r: "踩香蕉皮滑倒的连环倒霉场景滑稽，『倒霉/运气差』邻域直达。" },
  "假日": { o: "REDUNDANT", c: "放假" },
  "假装": { o: "KEEP", d: "normal", t: ["drawable", "action"], r: "偷瞄装睡等戏剧性场景进入『装/假装』邻域，表演空间大。" },
  "依偎": { o: "REDUNDANT", c: "拥抱" },
  "住宅": { o: "REDUNDANT", c: "房子" },
  "供品": { o: "REVIEW", r: "祭桌场景民俗感强但语境偏严肃，是否适合家庭游戏需判断。" },
  "使劲": { o: "KEEP", d: "normal", t: ["drawable", "action"], r: "咬牙搬抬画面直观，作用力簇代表词，『用力/使劲』邻域命中。" },
  "侄子": { o: "REDUNDANT", c: "弟弟" },
  "偷偷": { o: "KEEP", d: "normal", t: ["drawable", "action"], r: "踮脚溜走画面生动，作悄悄簇代表，『偷偷/悄悄』邻域即命中。" },
  "傲慢": { o: "REDUNDANT", c: "骄傲" },
  "僵硬": { o: "KEEP", d: "normal", t: ["drawable", "action"], r: "机器人式直挺走路滑稽，『僵硬/硬邦邦』邻域可达。" },
  "光滑": { o: "KEEP", d: "normal", t: ["drawable"], r: "滑梯/冰面顺滑质感可画，『滑/光滑』邻域命中。" },
  "光芒": { o: "REDUNDANT", c: "阳光" },
  "公园": { o: "KEEP", d: "easy", t: ["drawable", "place"], r: "绿地长椅游乐设施组合进入『公园』邻域，儿童高频场所。" },
  "先生": { o: "REDUNDANT", c: "老师" },
  "兴奋": { o: "KEEP", d: "normal", t: ["drawable", "emotion"], r: "举臂欢呼画面直达，作激动簇代表。" },
  "养病": { o: "REDUNDANT", c: "医生看病" },
  "农具": { o: "REDUNDANT", c: "锄头" },
  "典礼": { o: "KEEP", d: "hard", t: ["drawable", "festival"], r: "礼堂授证场景进入『典礼/仪式』邻域。" },
  "功课": { o: "REDUNDANT", c: "看书" },
  "冲击": { o: "REVIEW", r: "半抽象动词，巨浪撞击画面会漂到『海浪/撞』，独立成题价值存疑。" },
  "冲刷": { o: "REVIEW", r: "动作依附水流场景，画面漂向『瀑布/冲洗』，独立游戏体验弱。" },
  "决心": { o: "REVIEW", r: "握拳坚定是通用手势，难以构成独立游戏画面。" },
  "冷笑": { o: "KEEP", d: "normal", t: ["drawable", "emotion"], r: "撇嘴冷笑表情有戏剧感，『冷笑/坏笑』邻域命中。" },
  "凌乱": { o: "KEEP", d: "normal", t: ["drawable", "home"], r: "满地散乱杂物画面直观，作乱簇代表，『乱/乱七八糟』邻域即命中。" },
  "凝视": { o: "REDUNDANT", c: "观察" },
  "凶狠": { o: "REDUNDANT", c: "凶猛" },
  "凶猛": { o: "KEEP", d: "normal", t: ["drawable", "animal"], r: "猛兽扑咬气势可画，作凶簇代表，『凶/凶猛』邻域命中。" },
  "初夏": { o: "REDUNDANT", c: "夏天" },
  "剩饭": { o: "KEEP", d: "normal", t: ["drawable", "food"], r: "碗底剩饭餐桌场景生活化，『剩饭/剩菜』邻域即命中。" },
  "前肢": { o: "REVIEW", r: "解剖学术语，画面只能落到爪子/前腿，作题价值低。" },
  "包袱": { o: "KEEP", d: "normal", t: ["drawable", "object"], r: "布包袱挑担形象经典，『包袱/行李卷』邻域可达。" },
  "匪徒": { o: "REJECT", r: "持械罪犯题材，暴力色彩与家庭游戏氛围不符。" },
  "卫生": { o: "REDUNDANT", c: "洗手" },
  "历史": { o: "KEEP", d: "normal", t: ["drawable", "culture"], r: "古卷/朝代更迭示意进入『历史/古代』邻域。" },
  "厌烦": { o: "REDUNDANT", c: "讨厌" },
  "讨厌": { o: "KEEP", d: "normal", t: ["drawable", "emotion"], r: "嫌弃摆手表情直观，作厌烦簇代表，『讨厌/烦』邻域命中。" },
  "原始": { o: "REVIEW", r: "画面会落到『原始人』而非『原始』本身，属性词独立成题弱。" },
  "发明": { o: "KEEP", d: "normal", t: ["drawable", "science"], r: "发明家与奇巧装置场景进入『发明/创造』邻域，画法自由度大。" },
  "发现": { o: "KEEP", d: "normal", t: ["drawable", "action"], r: "放大镜惊喜瞬间进入『发现/找到了』邻域。" },
  "发誓": { o: "KEEP", d: "normal", t: ["drawable", "action"], r: "举手郑重起誓姿态明确，『发誓/保证』邻域命中。" },
  "发颤": { o: "REDUNDANT", c: "发抖" },
  "叔叔": { o: "KEEP", d: "easy", t: ["drawable", "person"], r: "作男性平辈亲属称谓代表词，画面进入『叔叔』邻域即命中。" },
  "变化": { o: "KEEP", d: "normal", t: ["drawable"], r: "前后对比箭头画法直观，作改变簇代表，『变化/变了』邻域命中。" },
  "古代": { o: "KEEP", d: "normal", t: ["drawable", "culture"], r: "古装宫殿场景进入『古代/古时候』邻域。" },
  "吆喝": { o: "KEEP", d: "normal", t: ["drawable", "person"], r: "摊贩叫卖姿态生动，『叫卖/吆喝』邻域可达。" },
  "合力": { o: "KEEP", d: "normal", t: ["drawable", "action"], r: "众人合力抬物画面明确，作合作簇代表，『一起搬/合作』邻域命中。" },
  "合奏": { o: "REDUNDANT", c: "弹琴" },
  "含笑": { o: "REDUNDANT", c: "笑嘻嘻" },
  "吸收": { o: "KEEP", d: "normal", t: ["drawable", "science"], r: "海绵吸水等示意进入『吸/吸收』邻域。" },
  "吹拂": { o: "REDUNDANT", c: "微风" },
  "吼叫": { o: "KEEP", d: "normal", t: ["drawable", "animal"], r: "猛兽张口吼叫气势足，作吼簇代表，『吼/咆哮』邻域即命中。" },
  "周游": { o: "REDUNDANT", c: "旅行" },
  "味道": { o: "KEEP", d: "easy", t: ["drawable", "food"], r: "品尝反应画面直观，『味道/尝』邻域即命中。" },
  "呼吸": { o: "KEEP", d: "normal", t: ["drawable", "body"], r: "深呼吸吐纳姿态可画，『呼吸/喘气』邻域可达。" },
  "呼唤": { o: "REVIEW", r: "呼喊招手画面漂向『喊/叫』，独立游戏体验单薄。" },
  "咆哮": { o: "REDUNDANT", c: "吼叫" },
  "和蔼": { o: "REDUNDANT", c: "慈祥" },
  "慈祥": { o: "KEEP", d: "normal", t: ["drawable", "person"], r: "老人和善笑容明确，作和蔼簇代表，『慈祥/和蔼』邻域命中。" },
  "喧闹": { o: "REDUNDANT", c: "热闹" },
  "热闹": { o: "KEEP", d: "easy", t: ["drawable", "festival"], r: "市集人声鼎沸场景进入『热闹/人多』邻域，作喧闹簇代表。" },
  "喉咙": { o: "REDUNDANT", c: "嗓子" },
  "嗓子": { o: "KEEP", d: "easy", t: ["drawable", "body"], r: "捂嗓歌唱/大声朗读画面进入『嗓子/喉咙』邻域，作代表词。" },
  "嘴唇": { o: "KEEP", d: "easy", t: ["drawable", "body"], r: "红唇特写直观，『嘴唇/嘴』邻域即命中。" },
  "嘴角": { o: "REDUNDANT", c: "嘴唇" },
  "噪声": { o: "REVIEW", r: "捂耳嘈杂画面漂向『吵/噪音』，声音类抽象词独立成题价值存疑。" },
  "喜悦": { o: "REDUNDANT", c: "快活" },
  "喜爱": { o: "REDUNDANT", c: "爱心" },
  "回忆": { o: "KEEP", d: "normal", t: ["drawable", "emotion"], r: "回忆泡泡画法直观，作记忆簇代表，『回忆/想起』邻域命中。" },
  "团圆": { o: "REDUNDANT", c: "中秋" },
  "团结": { o: "REDUNDANT", c: "合力" },
  "困难": { o: "KEEP", d: "normal", t: ["drawable", "emotion"], r: "抓头苦想/难题关卡进入『困难/难题』邻域，作艰难簇代表。" },
  "图画": { o: "REDUNDANT", c: "画画" },
  "圆盘": { o: "REDUNDANT", c: "盘子" },
  "地板": { o: "KEEP", d: "easy", t: ["drawable", "home"], r: "木纹地面特写可画，『地板/地面』邻域即命中。" },
  "地道": { o: "REDUNDANT", c: "隧道" },
  "坚持": { o: "REVIEW", r: "咬牙坚持与加油画面重合，抽象意志词独立成题弱。" },
  "坚硬": { o: "KEEP", d: "normal", t: ["drawable"], r: "敲石不碎/硬物对比进入『硬/坚硬』邻域。" },
  "墙壁": { o: "KEEP", d: "normal", t: ["drawable", "place"], r: "砖墙特写直观，作墙簇代表，『墙/墙壁』邻域即命中。" },
  "壮观": { o: "KEEP", d: "normal", t: ["drawable", "place"], r: "宏大场面（瀑布/群山）直观，作雄伟簇代表，『壮观/宏伟』邻域命中。" },
  "声音": { o: "KEEP", d: "normal", t: ["drawable", "object"], r: "音符+声波符号组合进入『声音/响』邻域。" },
  "夜幕": { o: "REDUNDANT", c: "夜晚" },
  "夜晚": { o: "KEEP", d: "easy", t: ["drawable", "nature"], r: "月亮星星夜景直观，作夜间时辰簇代表，『夜晚/晚上』邻域即命中。" },
  "大厅": { o: "REDUNDANT", c: "客厅" },
  "大叔": { o: "REDUNDANT", c: "叔叔" },
  "大师": { o: "REDUNDANT", c: "师傅" },
  "师傅": { o: "KEEP", d: "normal", t: ["drawable", "person"], r: "匠人师傅形象可画，作师徒簇代表，『师傅/师父』邻域命中。" },
  "大臣": { o: "KEEP", d: "hard", t: ["drawable", "culture"], r: "朝服官帽拱手形象进入『大臣/官员』邻域，古装剧认知度高。" },
  "太太": { o: "REVIEW", r: "旧式称谓，画面漂向『夫人/奶奶/阿姨』，无从锁定。" },
  "失明": { o: "REDUNDANT", c: "盲人" },
  "盲人": { o: "KEEP", d: "normal", t: ["drawable", "person"], r: "拄杖闭眼行走形象经典，作视障簇代表，『盲人/看不见』邻域命中。" },
  "失望": { o: "KEEP", d: "normal", t: ["drawable", "emotion"], r: "垂头丧气神态直观，『失望/失落』邻域即命中。" },
  "头痛": { o: "KEEP", d: "normal", t: ["drawable", "body"], r: "头部闪电+抱头符号卡通通用，『头痛/头疼』邻域即命中。" },
  "夸奖": { o: "KEEP", d: "normal", t: ["drawable", "emotion"], r: "竖指称赞姿态明确，作夸赞簇代表，『表扬/夸奖』邻域命中。" },
  "好奇": { o: "KEEP", d: "normal", t: ["drawable", "emotion"], r: "圆睁双眼+问号符号经典，『好奇/想知道』邻域即命中。" },
  "奇幻": { o: "KEEP", d: "normal", t: ["drawable", "culture"], r: "城堡巨龙魔法世界进入『奇幻/魔法世界』邻域，画法自由。" },
  "奇观": { o: "REDUNDANT", c: "壮观" },
  "妒忌": { o: "KEEP", d: "normal", t: ["drawable", "emotion"], r: "斜眼嫉妒神态有戏剧性，『嫉妒/眼红』邻域命中。" },
  "妹妹": { o: "KEEP", d: "easy", t: ["drawable", "person"], r: "作女孩亲属称谓代表，画小女孩即进入『妹妹/女孩』邻域。" },
  "妻子": { o: "REDUNDANT", c: "新娘" },
  "姑娘": { o: "REDUNDANT", c: "妹妹" },
  "姑父": { o: "REDUNDANT", c: "叔叔" },
  "姿势": { o: "KEEP", d: "normal", t: ["drawable", "action"], r: "定格造型画面直观，『姿势/造型』邻域即命中。" },
  "威武": { o: "KEEP", d: "normal", t: ["drawable", "person"], r: "铠甲昂立气势可画，作威风簇代表（含四字威风凛凛），『威武/威风』邻域命中。" },
  "媳妇": { o: "REDUNDANT", c: "新娘" },
  "子孙": { o: "KEEP", d: "normal", t: ["drawable", "person"], r: "几代同堂家族树画面进入『子孙/后代』邻域。" },
  "季节": { o: "KEEP", d: "normal", t: ["drawable", "nature"], r: "四季拼图画法直观，『四季/季节』邻域即命中。" },
  "孤独": { o: "KEEP", d: "normal", t: ["drawable", "emotion"], r: "独坐角落画面有感染力，作寂寞簇代表，『孤单/孤独』邻域命中。" },
  "学习": { o: "REDUNDANT", c: "看书" },
  "宁静": { o: "REDUNDANT", c: "安静" },
  "宅院": { o: "REDUNDANT", c: "房子" },
  "安静": { o: "KEEP", d: "easy", t: ["drawable", "emotion"], r: "嘘声手势/无声场景直观，作静簇代表，『安静/静悄悄』邻域即命中。" },
  "宏伟": { o: "REDUNDANT", c: "壮观" },
  "宝库": { o: "REDUNDANT", c: "宝石" },
  "害怕": { o: "KEEP", d: "easy", t: ["drawable", "emotion"], r: "抱头瑟缩形象通用，作恐惧簇代表，『害怕/吓到了』邻域即命中。" },
  "宽慰": { o: "REVIEW", r: "安慰拍肩画面漂向『安慰/拍拍』，情感动词独立成题弱。" },
  "宽广": { o: "REDUNDANT", c: "宽阔" },
  "宽阔": { o: "KEEP", d: "normal", t: ["drawable", "nature"], r: "大路广场开阔感可画，作宽簇代表，『宽阔/辽阔』邻域命中。" },
  "寂寞": { o: "REDUNDANT", c: "孤独" },
  "寂静": { o: "REDUNDANT", c: "安静" },
  "寄宿": { o: "REVIEW", r: "集体宿舍场景概念偏校园制度，儿童独立作题价值存疑。" },
  "对岸": { o: "KEEP", d: "normal", t: ["drawable", "nature"], r: "隔河相望构图直观，『对岸/河那边』邻域即命中。" },
  "寻找": { o: "KEEP", d: "easy", t: ["drawable", "action"], r: "翻找搜寻+问号画面经典，『找/寻找』邻域即命中。" },
  "小心": { o: "REDUNDANT", c: "危险" },
  "尖叫": { o: "KEEP", d: "normal", t: ["drawable", "action"], r: "过山车张口尖叫场景有感染力，『尖叫/大叫』邻域命中。" },
  "尘土": { o: "REDUNDANT", c: "灰尘" },
  "尽头": { o: "KEEP", d: "normal", t: ["drawable", "place"], r: "道路消失远方构图直观，『尽头/终点』邻域即命中。" },
  "尽情": { o: "KEEP", d: "normal", t: ["drawable", "emotion"], r: "撒欢尽兴玩耍画面进入『尽情/痛快玩』邻域。" },
  "局促": { o: "REDUNDANT", c: "紧张" },
  "紧张": { o: "KEEP", d: "normal", t: ["drawable", "emotion"], r: "搓手冒汗神态通用，作紧张簇代表，『紧张/不安』邻域即命中。" },
  "屏息": { o: "KEEP", d: "normal", t: ["drawable", "action"], r: "捂鼻屏气定格姿态有戏剧张力，『屏住呼吸/憋气』邻域命中。" },
  "屏障": { o: "REVIEW", r: "书面比喻词，群山如屏画面漂向『大山/遮挡』。" },
  "山川": { o: "KEEP", d: "normal", t: ["drawable", "nature"], r: "山河全景画法经典，『山水/山川』邻域即命中。" },
  "山洪": { o: "REDUNDANT", c: "洪水" },
  "山涧": { o: "REDUNDANT", c: "溪流" },
  "崩塌": { o: "KEEP", d: "normal", t: ["drawable", "nature"], r: "山石崩落画面有冲击力，『塌了/崩塌』邻域即命中。" },
  "工具": { o: "KEEP", d: "easy", t: ["drawable", "tool"], r: "工具箱摊开画面直观，『工具/工具箱』邻域即命中。" },
  "工夫": { o: "REDUNDANT", c: "武术" },
  "布料": { o: "KEEP", d: "normal", t: ["drawable", "object"], r: "成卷布匹可画，『布料/布』邻域即命中，作布绸簇代表。" },
  "布置": { o: "KEEP", d: "normal", t: ["drawable", "home"], r: "挂饰摆场场景直观，作装饰簇代表，『布置/装饰』邻域命中。" },
  "希望": { o: "KEEP", d: "normal", t: ["drawable", "emotion"], r: "幼苗破土/眺望远方进入『希望/盼望』邻域，作盼簇代表。" },
  "帐子": { o: "REDUNDANT", c: "帐篷" },
  "席子": { o: "REDUNDANT", c: "垫子" },
  "帮助": { o: "KEEP", d: "normal", t: ["drawable", "action"], r: "扶助提物姿态明确，作帮簇代表，『帮忙/帮助』邻域即命中。" },
  "帮忙": { o: "REDUNDANT", c: "帮助" },
  "干净": { o: "REDUNDANT", c: "扫地" },
  "干燥": { o: "REDUNDANT", c: "干旱" },
  "平稳": { o: "REDUNDANT", c: "平衡" },
  "平衡": { o: "KEEP", d: "normal", t: ["drawable", "sports"], r: "独木桩金鸡独立直观，『平衡/稳』邻域即命中，作平衡簇代表。" },
  "年纪": { o: "REDUNDANT", c: "年龄" },
  "年龄": { o: "KEEP", d: "normal", t: ["drawable", "body"], r: "生日蜡烛数/成长阶梯画法进入『年龄/几岁』邻域，作代表词。" },
  "幸福": { o: "KEEP", d: "easy", t: ["drawable", "emotion"], r: "全家相拥温馨画面进入『幸福/温馨』邻域即命中，v1 的词面歧义扣分不再适用。" },
  "幸运": { o: "KEEP", d: "normal", t: ["drawable", "emotion"], r: "四叶草/中奖欢呼进入『幸运/好运』邻域。" },
  "幻想": { o: "REDUNDANT", c: "梦想" },
  "梦想": { o: "KEEP", d: "normal", t: ["drawable", "emotion"], r: "追梦飞翔比喻画面经典，作幻想簇代表，『梦想/理想』邻域命中。" },
  "幼儿": { o: "REDUNDANT", c: "婴儿" },
  "幽静": { o: "REDUNDANT", c: "安静" },
  "广播": { o: "REDUNDANT", c: "收音机" },
  "庄稼": { o: "KEEP", d: "normal", t: ["drawable", "plant"], r: "田间庄稼直观且口语常用，作农作物簇代表，『庄稼/农作物』邻域即命中。" },
  "床铺": { o: "REDUNDANT", c: "床" },
  "座位": { o: "REDUNDANT", c: "椅子" },
  "建筑": { o: "REDUNDANT", c: "高楼" },
  "弟弟": { o: "KEEP", d: "easy", t: ["drawable", "person"], r: "作男孩亲属称谓代表，画小男孩即进入『弟弟/男孩』邻域。" },
  "张开": { o: "REVIEW", r: "泛义动词，张嘴张臂画面无法构成独立游戏体验。" },
  "彩排": { o: "REDUNDANT", c: "排练" },
  "排练": { o: "KEEP", d: "normal", t: ["drawable", "school"], r: "演前走位排练场景直观，作排簇代表，『排练/彩排』邻域即命中。" },
  "彩绘": { o: "REDUNDANT", c: "画画" },
  "彩色": { o: "REDUNDANT", c: "彩虹" },
  "徒弟": { o: "KEEP", d: "normal", t: ["drawable", "person"], r: "拜师学艺场景进入『徒弟/学徒』邻域。" },
  "徘徊": { o: "REVIEW", r: "来回踱步画面漂向『走来走去』，书面词儿童不熟。" },
  "微笑": { o: "REDUNDANT", c: "笑嘻嘻" },
  "微风": { o: "KEEP", d: "normal", t: ["drawable", "weather"], r: "柳枝轻摆/发丝飘动进入『微风/轻风』邻域，作风簇代表。" },
  "心事": { o: "REDUNDANT", c: "担心" },
  "心情": { o: "REDUNDANT", c: "表情" },
  "表情": { o: "KEEP", d: "easy", t: ["drawable", "emotion"], r: "喜怒表情脸谱直观，『表情/脸色』邻域即命中，作心情簇代表。" },
  "心疼": { o: "KEEP", d: "normal", t: ["drawable", "emotion"], r: "搂抱受伤孩子神情进入『心疼/疼爱』邻域。" },
  "忘记": { o: "KEEP", d: "normal", t: ["drawable", "emotion"], r: "挠头想不起+头顶问号经典，『忘了/忘记』邻域即命中。" },
  "忙乱": { o: "REDUNDANT", c: "忙碌" },
  "忙碌": { o: "KEEP", d: "normal", t: ["drawable", "action"], r: "多线奔忙画面直观，作忙簇代表，『忙/忙碌』邻域即命中。" },
  "忧伤": { o: "REDUNDANT", c: "痛苦" },
  "忧虑": { o: "REDUNDANT", c: "担心" },
  "担心": { o: "KEEP", d: "normal", t: ["drawable", "emotion"], r: "忧心张望神态直观，作担忧簇代表，『担心/担心』邻域即命中。" },
  "快活": { o: "KEEP", d: "easy", t: ["drawable", "emotion"], r: "蹦跳欢笑画面直观口语，作欢乐簇代表，『快活/开心』邻域即命中。" },
  "念叨": { o: "KEEP", d: "normal", t: ["drawable", "action"], r: "絮叨说话神态有生活气息，『念叨/唠叨』邻域命中。" },
  "怒吼": { o: "REDUNDANT", c: "吼叫" },
  "恐怖": { o: "REJECT", r: "惊悚恐怖氛围与轻松亲子游戏不符。" },
  "恐惧": { o: "REDUNDANT", c: "害怕" },
  "恢复": { o: "REVIEW", r: "复原过程抽象，箭头示意漂向『变回/复原』，独立成题弱。" },
  "悲惨": { o: "REDUNDANT", c: "痛苦" },
  "悲痛": { o: "REDUNDANT", c: "痛苦" },
  "惊叹": { o: "REDUNDANT", c: "大吃一惊" },
  "惊奇": { o: "REDUNDANT", c: "大吃一惊" },
  "惊惶": { o: "REDUNDANT", c: "害怕" },
  "惊慌": { o: "REDUNDANT", c: "害怕" },
  "感动": { o: "KEEP", d: "normal", t: ["drawable", "emotion"], r: "热泪盈眶+暖心场景进入『感动/暖心』邻域。" },
  "感叹": { o: "REDUNDANT", c: "叹气" },
  "感激": { o: "KEEP", d: "normal", t: ["drawable", "emotion"], r: "拱手感念姿态进入『感激/感谢』邻域。" },
  "慌忙": { o: "REDUNDANT", c: "急急忙忙" },
  "懒惰": { o: "KEEP", d: "easy", t: ["drawable", "emotion"], r: "瘫沙发吃零食形象滑稽，『懒/懒惰』邻域即命中。" },
  "懦弱": { o: "REDUNDANT", c: "胆小" },
  "戏耍": { o: "REDUNDANT", c: "玩耍" },
  "玩耍": { o: "KEEP", d: "easy", t: ["drawable", "action"], r: "嬉戏玩乐场景直观，作玩簇代表，『玩耍/玩』邻域即命中。" },
  "成熟": { o: "KEEP", d: "normal", t: ["drawable", "plant"], r: "果实由青转红进入『熟了/成熟』邻域。" },
  "成绩": { o: "KEEP", d: "normal", t: ["drawable", "school"], r: "满分试卷+欢呼进入『成绩/考分』邻域。" },
  "扇动": { o: "REVIEW", r: "动作依附翅膀，画面漂向『扇翅膀/飞』，独立成题弱。" },
  "手艺": { o: "REVIEW", r: "泛称技艺，画面只能落到具体手工，儿童独立作题价值低。" },
  "扑打": { o: "REDUNDANT", c: "扑腾" },
  "扑腾": { o: "KEEP", d: "normal", t: ["drawable", "action"], r: "落水扑腾/雏鸟扑翅画面生动，作扑簇代表，『扑腾/扑腾』邻域即命中。" },
  "打猎": { o: "REVIEW", r: "画面清晰但含持械猎杀场景，按 v1.1 暴力邻域规则交人工判断家庭适配性。" },
  "拍打": { o: "REVIEW", r: "泛义拍击动作，画面漂向『拍手/拍打灰尘』，独立成题弱。" },
  "拍摄": { o: "REDUNDANT", c: "拍照" },
  "拒绝": { o: "KEEP", d: "normal", t: ["drawable", "action"], r: "双手交叉摆手+摇头姿态明确，『拒绝/不要』邻域即命中。" },
  "拘束": { o: "REDUNDANT", c: "紧张" },
  "招待": { o: "KEEP", d: "normal", t: ["drawable", "home"], r: "奉茶让座待客场景直观，『招待/请客』邻域命中。" },
  "招引": { o: "REVIEW", r: "招手引逗画面漂向『招手/吸引』，独立成题弱。" },
  "拥挤": { o: "REDUNDANT", c: "人山人海" },
  "拨动": { o: "REVIEW", r: "泛义小动作，画面漂向『拨/弹』，独立成题弱。" },
  "拼命": { o: "REDUNDANT", c: "使劲" },
  "指点": { o: "REVIEW", r: "手指指引画面漂向『指路/指』，独立成题弱。" },
  "挡住": { o: "REDUNDANT", c: "阻挡" },
  "阻挡": { o: "KEEP", d: "normal", t: ["drawable", "action"], r: "伸手拦截/球门扑救姿态明确，作挡簇代表，『挡住/拦住』邻域即命中。" },
  "挣扎": { o: "REDUNDANT", c: "扑腾" },
  "挣钱": { o: "REVIEW", r: "打工赚钱场景漂向『工作/赚钱』，涉及金钱价值观，交人工判断。" },
  "挤压": { o: "REVIEW", r: "物理动作抽象，画面漂向『压/挤』，独立成题弱。" },
  "掌声": { o: "REDUNDANT", c: "拍手" },
  "排列": { o: "REDUNDANT", c: "排队" },
  "探望": { o: "KEEP", d: "normal", t: ["drawable", "action"], r: "拎果探病/登门拜访场景直观，『探望/看望』邻域即命中。" },
  "接触": { o: "REVIEW", r: "指尖相触画面语义宽泛，独立成题弱。" },
  "提前": { o: "REVIEW", r: "时间先后概念抽象，画面依赖钟表对比，独立成题弱。" },
  "提示": { o: "REVIEW", r: "元语言词（关于游戏本身的词），画面漂向『暗示/提醒』。" },
  "搅和": { o: "KEEP", d: "normal", t: ["drawable", "food"], r: "搅盆和面场景生活化，『搅拌/搅和』邻域即命中。" },
  "搏斗": { o: "REJECT", r: "打斗扭打为直接暴力内容，与家庭游戏氛围不符。" },
  "搬运": { o: "KEEP", d: "normal", t: ["drawable", "action"], r: "扛箱搬柜姿态明确，『搬东西/搬运』邻域即命中。" },
  "搭乘": { o: "REVIEW", r: "画面漂向『坐车/上车』，依附具体交通工具，独立成题弱。" },
  "敌人": { o: "REVIEW", r: "对阵场面含冲突对抗，是否适合家庭氛围交人工判断。" },
  "敬佩": { o: "REVIEW", r: "敬佩注目画面漂向『佩服/尊敬』，情感强度词独立成题弱。" },
  "敬爱": { o: "REVIEW", r: "敬爱之情难以从画面区分于尊敬/喜爱。" },
  "数落": { o: "REDUNDANT", c: "教训" },
  "教训": { o: "KEEP", d: "normal", t: ["drawable", "school"], r: "训导批评场景直观，作责备簇代表，『教训/批评』邻域即命中。" },
  "整洁": { o: "REDUNDANT", c: "扫地" },
  "文静": { o: "REVIEW", r: "性格特质词，安静女孩画面漂向『安静/淑女』，独立锁定难。" },
  "斑点": { o: "KEEP", d: "normal", t: ["drawable", "animal"], r: "斑点狗/瓢虫圆点直观，『斑点/斑点狗』邻域命中。" },
  "新鲜": { o: "KEEP", d: "normal", t: ["drawable", "food"], r: "带露果蔬进入『新鲜/水灵』邻域。" },
  "朝霞": { o: "REDUNDANT", c: "晚霞" },
  "朝鲜": { o: "REVIEW", r: "依赖国旗符号识别，属地理标志而非画猜。" },
  "期待": { o: "REDUNDANT", c: "希望" },
  "朦胧": { o: "REDUNDANT", c: "模糊" },
  "模糊": { o: "KEEP", d: "normal", t: ["drawable"], r: "虚化轮廓/雾中景象画法明确，作朦胧簇代表，『模糊/看不清』邻域即命中。" },
  "机灵": { o: "KEEP", d: "easy", t: ["drawable", "emotion"], r: "转动机敏眼神+灵光符号进入『机灵/聪明』邻域，作聪慧簇代表。" },
  "杀菌": { o: "KEEP", d: "normal", t: ["drawable", "science"], r: "肥皂消灭卡通细菌有趣味性，『杀菌/消毒』邻域命中。" },
  "杏花": { o: "REDUNDANT", c: "桃花" },
  "杜鹃": { o: "REVIEW", r: "杜鹃鸟与杜鹃花双关，同一画面无法指向确定语义。" },
  "松手": { o: "KEEP", d: "normal", t: ["drawable", "action"], r: "松开放手瞬间可画，『松手/放手』邻域即命中。" },
  "松脂": { o: "REVIEW", r: "树脂细节儿童陌生，画面难以独立成题。" },
  "松针": { o: "REDUNDANT", c: "松树" },
  "板凳": { o: "REDUNDANT", c: "椅子" },
  "果树": { o: "REDUNDANT", c: "果园" },
  "枝干": { o: "REDUNDANT", c: "树枝" },
  "枝条": { o: "REDUNDANT", c: "树枝" },
  "树梢": { o: "REDUNDANT", c: "树枝" },
  "树苗": { o: "REDUNDANT", c: "种树" },
  "桂花": { o: "REDUNDANT", c: "桃花" },
  "桅杆": { o: "REVIEW", r: "船只部件，画面漂向『船/旗杆』，独立成题弱。" },
  "梅花": { o: "KEEP", d: "normal", t: ["drawable", "plant"], r: "寒枝梅花与春日桃花视觉可分，作花簇第二代表，『梅花/腊梅』邻域命中。" },
  "检查": { o: "KEEP", d: "normal", t: ["drawable", "school"], r: "持板查验/体检场景直观，『检查/体检』邻域即命中。" },
  "检阅": { o: "REVIEW", r: "阅兵检阅场面偏正式宏大，儿童作画与猜认难度高。" },
  "植树": { o: "REDUNDANT", c: "种树" },
  "楼梯": { o: "REDUNDANT", c: "台阶" },
  "榕树": { o: "REDUNDANT", c: "树林" },
  "榨油": { o: "REVIEW", r: "行业工序场景儿童陌生，独立成题价值低。" },
  "模型": { o: "KEEP", d: "normal", t: ["drawable", "object"], r: "航模船模拼装场景进入『模型/拼装玩具』邻域。" },
  "欢快": { o: "REDUNDANT", c: "快活" },
  "欣赏": { o: "REDUNDANT", c: "观察" },
  "欺负": { o: "REVIEW", r: "欺凌场景负面，程度拿捏需家长判断。" },
  "歇凉": { o: "KEEP", d: "normal", t: ["drawable", "nature"], r: "树荫摇扇纳凉场景直观，『乘凉/歇凉』邻域命中。" },
  "歌唱": { o: "REDUNDANT", c: "唱歌" },
  "歌声": { o: "REDUNDANT", c: "唱歌" },
  "殿堂": { o: "REDUNDANT", c: "故宫" },
  "毁坏": { o: "REDUNDANT", c: "粉碎" },
  "粉碎": { o: "KEEP", d: "normal", t: ["drawable", "action"], r: "摔杯碎裂瞬间画面明确，作碎簇代表，『打碎/粉碎』邻域即命中。" },
  "破裂": { o: "REDUNDANT", c: "粉碎" },
  "母亲": { o: "REDUNDANT", c: "妈妈" },
  "毛虫": { o: "REDUNDANT", c: "毛毛虫" },
  "毡帽": { o: "REDUNDANT", c: "帽子" },
  "气味": { o: "REDUNDANT", c: "味道" },
  "氧气": { o: "REVIEW", r: "气体不可见，氧气瓶/气泡画面漂向『气泡/潜水』。" },
  "求饶": { o: "REVIEW", r: "跪地讨饶含威压场景，负面程度需家长判断。" },
  "汇集": { o: "REDUNDANT", c: "聚集" },
  "汗毛": { o: "REVIEW", r: "体毛特写作题怪异，儿童独立作画价值低。" },
  "河床": { o: "REVIEW", r: "地理术语，画面漂向『干涸的河』，儿童陌生。" },
  "河水": { o: "REDUNDANT", c: "小河" },
  "河流": { o: "REDUNDANT", c: "小河" },
  "河滩": { o: "REDUNDANT", c: "沙滩" },
  "沸腾": { o: "KEEP", d: "normal", t: ["drawable", "food"], r: "开水翻滚气泡画面直观，『烧开/沸腾』邻域即命中。" },
  "治疗": { o: "REDUNDANT", c: "医生看病" },
  "法庭": { o: "REVIEW", r: "庭审场景偏成人化，儿童熟悉度低。" },
  "波涛": { o: "REDUNDANT", c: "海浪拍岸" },
  "波纹": { o: "KEEP", d: "normal", t: ["drawable", "nature"], r: "水纹扩散画法经典，作涟漪簇代表，『波纹/涟漪』邻域即命中。" },
  "注意": { o: "REDUNDANT", c: "危险" },
  "泪水": { o: "REDUNDANT", c: "哭泣" },
  "洒落": { o: "REVIEW", r: "散落动作依附具体物，画面漂向『撒/掉了』，独立成题弱。" },
  "洞穴": { o: "REDUNDANT", c: "山洞" },
  "活泼": { o: "REDUNDANT", c: "快活" },
  "流淌": { o: "REDUNDANT", c: "溪流" },
  "浑浊": { o: "REVIEW", r: "水质形容词，画面漂向『脏水』，独立成题弱。" },
  "浪漫": { o: "REVIEW", r: "氛围抽象词，玫瑰烛光画面语义宽泛。" },
  "浮动": { o: "REDUNDANT", c: "飘浮" },
  "浴桶": { o: "REDUNDANT", c: "洗澡" },
  "海参": { o: "REVIEW", r: "海洋生物儿童熟悉度低，形象难以独立识别。" },
  "海底": { o: "KEEP", d: "normal", t: ["drawable", "nature"], r: "鱼群珊瑚水下世界进入『海底/海里』邻域。" },
  "海滨": { o: "REDUNDANT", c: "沙滩" },
  "消化": { o: "REVIEW", r: "生理科普图示，作题体验偏课堂。" },
  "消失": { o: "KEEP", d: "normal", t: ["drawable", "science"], r: "渐隐/魔术消失画面有趣，『消失/不见了』邻域即命中。" },
  "涨潮": { o: "REDUNDANT", c: "潮汐" },
  "淘气": { o: "KEEP", d: "easy", t: ["drawable", "emotion"], r: "捣蛋恶作剧场景滑稽，作顽皮簇代表，『淘气/调皮』邻域即命中。" },
  "深夜": { o: "REDUNDANT", c: "夜晚" },
  "混乱": { o: "REDUNDANT", c: "凌乱" },
  "淹没": { o: "REDUNDANT", c: "洪水" },
  "清凉": { o: "KEEP", d: "normal", t: ["drawable", "weather"], r: "树荫西瓜蒲扇组合进入『凉快/清凉』邻域，作凉爽簇代表。" },
  "清新": { o: "REVIEW", r: "空气质量感受抽象，画面漂向『空气好』。" },
  "清晨": { o: "REDUNDANT", c: "早晨" },
  "清洁": { o: "REDUNDANT", c: "扫地" },
  "清爽": { o: "REDUNDANT", c: "清凉" },
  "清醒": { o: "REDUNDANT", c: "醒来" },
  "清香": { o: "REDUNDANT", c: "香味" },
  "香味": { o: "KEEP", d: "normal", t: ["drawable", "food"], r: "香气波纹+诱人食物组合直观，作香簇代表，『香/香味』邻域即命中。" },
  "渔民": { o: "REDUNDANT", c: "渔夫" },
  "温和": { o: "REDUNDANT", c: "温暖" },
  "温暖": { o: "KEEP", d: "easy", t: ["drawable", "emotion"], r: "围炉相拥暖意场景直观，作暖簇代表，『温暖/暖和』邻域即命中。" },
  "温柔": { o: "REVIEW", r: "特质形容词，轻声细语画面难以与亲切/和蔼区分。" },
  "游动": { o: "REVIEW", r: "泛义移动动词，画面漂向『游/移动』。" },
  "游戏": { o: "REVIEW", r: "元概念词，画面漂向『玩游戏/游戏机』，语义过宽。" },
  "湖面": { o: "REDUNDANT", c: "湖水" },
  "滚动": { o: "REVIEW", r: "滚动物理动作依附具体物，画面漂向『滚』。" },
  "满意": { o: "REVIEW", r: "点头微笑画面与开心/认可难以区分出独立体验。" },
  "满足": { o: "REVIEW", r: "心满意足神态与满意/开心重叠，独立锁定难。" },
  "滴答": { o: "REDUNDANT", c: "闹钟" },
  "漂亮": { o: "KEEP", d: "easy", t: ["drawable", "emotion"], r: "美丽事物+星星眼反应进入『漂亮/好看』邻域即命中。" },
  "漆黑": { o: "REDUNDANT", c: "黑暗" },
  "演奏": { o: "REDUNDANT", c: "弹琴" },
  "漫游": { o: "REDUNDANT", c: "旅行" },
  "潮湿": { o: "REDUNDANT", c: "湿淋淋" },
  "激动": { o: "REDUNDANT", c: "兴奋" },
  "火盆": { o: "REVIEW", r: "旧式取暖物件儿童陌生，画面漂向『烤火』。" },
  "灰尘": { o: "KEEP", d: "normal", t: ["drawable", "nature"], r: "尘埃飘散/拍打扬灰画面直观，作尘簇代表，『灰尘/尘土』邻域即命中。" },
  "灿烂": { o: "REVIEW", r: "形容光彩夺目，画面漂向『阳光/笑容』，独立锁定难。" },
  "炎夏": { o: "REDUNDANT", c: "炎热" },
  "炎热": { o: "KEEP", d: "normal", t: ["drawable", "weather"], r: "烈日当空+挥汗如雨进入『热/炎热』邻域，作热簇代表。" },
  "炭火": { o: "REDUNDANT", c: "火焰" },
  "烛光": { o: "REDUNDANT", c: "蜡烛" },
  "烟雾": { o: "REDUNDANT", c: "雾气" },
  "热情": { o: "KEEP", d: "normal", t: ["drawable", "emotion"], r: "热络迎客场景直观，作热烈簇代表，『热情/热心』邻域即命中。" },
  "热烈": { o: "REDUNDANT", c: "热情" },
  "焦急": { o: "KEEP", d: "normal", t: ["drawable", "emotion"], r: "来回踱步+看表神态直观，『着急/焦急』邻域即命中。" },
  "煤炭": { o: "REVIEW", r: "乌黑矿块画面漂向『煤/挖矿』，儿童作题价值低。" },
  "照耀": { o: "REVIEW", r: "光束笼罩画面漂向『阳光/照亮』，独立成题弱。" },
  "燃放": { o: "REDUNDANT", c: "鞭炮" },
  "爆发": { o: "REDUNDANT", c: "火山喷发" },
  "画纸": { o: "REVIEW", r: "一张白纸难以构成独立游戏画面。" },
  "画眉": { o: "REVIEW", r: "画眉鸟与描眉双关，同一画面语义不确定。" },
  "留意": { o: "REVIEW", r: "留意神态与注意/观察难以区分出独立体验。" },
  "留神": { o: "REVIEW", r: "同留意，泛注意类词独立成题弱。" },
  "疑问": { o: "KEEP", d: "normal", t: ["drawable", "emotion"], r: "头顶问号符号经典通用，『疑问/不懂』邻域即命中。" },
  "疙瘩": { o: "KEEP", d: "normal", t: ["drawable", "body"], r: "打结绳团/鼓包特写直观，『疙瘩/包』邻域命中。" },
  "疲倦": { o: "REDUNDANT", c: "筋疲力尽" },
  "疲劳": { o: "REDUNDANT", c: "筋疲力尽" },
  "疾病": { o: "REVIEW", r: "卧病场景负面基调，题材拿捏需家长判断。" },
  "痕迹": { o: "KEEP", d: "normal", t: ["drawable", "nature"], r: "脚印车辙等残留印记直观，作踪迹簇代表，『痕迹/印子』邻域即命中。" },
  "足迹": { o: "REDUNDANT", c: "痕迹" },
  "痛苦": { o: "KEEP", d: "normal", t: ["drawable", "emotion"], r: "捂脸皱眉神态通用，作悲簇代表，『痛苦/难受』邻域即命中。" },
  "瘦弱": { o: "KEEP", d: "normal", t: ["drawable", "body"], r: "细胳膊细腿形象可画，作虚弱簇代表，『瘦弱/单薄』邻域命中。" },
  "虚弱": { o: "REDUNDANT", c: "瘦弱" },
  "登陆": { o: "REVIEW", r: "抢滩登岸与登月双关，画面语义不确定。" },
  "白桦": { o: "REDUNDANT", c: "树林" },
  "白鹤": { o: "REDUNDANT", c: "丹顶鹤" },
  "盛开": { o: "REDUNDANT", c: "花朵" },
  "目光": { o: "REVIEW", r: "眼神特写画面语义宽泛，独立成题弱。" },
  "目标": { o: "REVIEW", r: "靶心画面漂向『射箭/靶子』，抽象目标义无法画。" },
  "相貌": { o: "REVIEW", r: "泛指长相，画面即一张脸，无从猜起。" },
  "相遇": { o: "KEEP", d: "normal", t: ["drawable", "action"], r: "两人相逢+惊叹号构图直观，『相遇/碰见』邻域即命中。" },
  "盼望": { o: "REDUNDANT", c: "希望" },
  "眺望": { o: "KEEP", d: "normal", t: ["drawable", "action"], r: "登高远望剪影直观，作远望簇代表，『眺望/远望』邻域即命中。" },
  "远眺": { o: "REDUNDANT", c: "眺望" },
  "眼泪": { o: "REDUNDANT", c: "哭泣" },
  "睁眼": { o: "KEEP", d: "easy", t: ["drawable", "body"], r: "闭眼到睁眼瞬间特写直观，『睁眼/睁开眼』邻域即命中。" },
  "睡莲": { o: "REDUNDANT", c: "荷花" },
  "瞄准": { o: "KEEP", d: "normal", t: ["drawable", "sports"], r: "眯眼对准+准星符号直观，『瞄准/对准』邻域即命中。" },
  "瞎闹": { o: "REDUNDANT", c: "淘气" },
  "石匠": { o: "REVIEW", r: "凿石职业儿童陌生，画面漂向『雕刻/工人』。" },
  "石油": { o: "REVIEW", r: "工业场景（钻井/油罐），儿童作题价值低。" },
  "石笋": { o: "REDUNDANT", c: "石钟乳" },
  "石级": { o: "REDUNDANT", c: "台阶" },
};
